#+TITLE: Εισαγωγική Διάλεξη
#+PROFESSOR: Κουγιουμτζής
#+COURSE: PTS
#+DATE: <2022-03-11 Fri>


* Γενικά περί μαθήματος
/Λίγο πολύ όλα τα εισαγωγικά φαίνεται να υπάρχουν στο elearning/

** Βαθμολογία
Στο μάθημα υπάρχουν δύο /εργασίες/ η μία με την μορφή κουίζ πάνω στο πρώτο μέρος
του μαθήματος ( πιθανότητες ), ενώ η δεύτερη με την μορφή προγράμματος πάνω στο
SPSS. Η κάθε μία εκ των εργασιών πιάνει 2 βαθμούς στον τελικό βαθμό του
μαθήματος ενώ οι υπόλοιποι 8 βαθμοί, προφανώς, δίνονται από τις τελικές εξετάσεις

** Ώρες
Υπήρξε μια /αλλαγή/ στις Δευτέρες (πιθανά για μόνο μία εβδομάδα), συμφωνα με την
οποία το μάθημα πάει από <2022-03-13 Sun 18:00-20:00> στις
<2022-03-13 Sun 17:00-19:00>.


** Βιβλία
Για βιβλία, ενθαρρύνεται η μελέτη με πολλά ηλεκτρονικά συγγράμματα από τον
Εύδοξο. Δίνονται τίτλοι και οδηγίες στο elearning του μαθήματος.

Ακόμα στο δεύτερο μέρος του μαθήματος έχει online σημειώσεις.

#+begin_comment
Έχοντας κατεβάσει όλα τα βιβλία (και κατόπιν μελετήσει για κάποιες ώρες από το
βιβλίο που /προτείνω/), με φάνηκε πως τουλάχιστον για το πρώτο μέρος του
μαθήματος, το βιβλίο των CarltonDevore(2017) είναι το ενδεδειγμένο.
#+end_comment

** Ύλη ( Συνοπτικά )
*** Πρώτο μέρος ( Θεωρία πιθανοτήτων )
1. Βασικές έννοιες πιθανότητας
2. Τυχαίες μεταβλητές και συναρτήσεις πιθανότητας
3. Θεωρητικές συναρτήσεις κατανομής και πυκνότητας
4. Συναρτήσεις τυχαίας μεταβλητής

*** Δεύτερο μέρος ( Στατιστική )
1. Περιγραφική στατιστική
2. Εκτίμηση παραμέτρων
3. Συσχέτιση και παλινδρόμηση

* Βασικές έννοιες
Σχεδόν όλα τα φαινόμενα που μπορεί κανείς να σκεφτεί δεν είναι βέβαιο ότι θα
συμβούν, απλά πιθανό. Οι πιθανότητες να γίνουν πραγματικότητα καθορίζονται από
ορισμένες παραμέτρους.

Έτσι, τα περισσότερα φαινόμενα, /αβέβαια ή τυχαία/, τα προσεγγίζουμε με την
χρήση /πιθανοκρατικών-στατιστικών/ μοντέλων, ενώ τα, ελάχιστα, /βέβαια/
φαινόμενα, όποια και αν είναι αυτά, τα προσεγγίζουμε με την χρήση καθοριστικών
μοντέλων.

** Τυχαιότητα $e$
Δεν ξέρω αν θα μπορούσε πιθανά να αναφέρεται σε ένα γενικότερο συντελεστή λάθους
/ απόκλισης, αντίστοιχου εκείνου που συχνά κανείς θα δεί σε διαλέξεις του Lewin.
Ειπώθηκε, πως στην πραγματικότητα είναι απειροελάχιστα τα φαινόμενα στους
υπολογισμούς των οποίων δεν είναι απαραίτητη η χρήση του /συντελεστή
τυχαιότητας/ $+e$

* Ορολογία
/Προτίμησα να προηγείται η ορολογία των παραδειγμάτων έτσι ώστε, αν κανείς
θέλει, να μπορεί να εξετάσει την κατανόηση της σε εκείνα/
- *Παράδειγμα - Experiment*
  Επαναλήψιμη διαδικασία με κάποιο αποτέλεσμα ( outcome )
- *Δειγματοχώρος - Sample space* $S$
  Το σύνολο των αποτελεσμάτων
- *Δειγματοσημείο - Sample point*
  Ένα εκ των αποτελεσμάτων
- *Γεγονός - Event*
  Ένα η περισσότερα αποτελέσματα ( καλώς ορισμένο σύνολο )


** Δυναμοσύνολο.
Το σύνολο πιθανών υποσυνόλων του $S$. Συνδέοντας το με την ορολογία που είδαμε
προηγουμένως, το $S$ είναι *βέβαιο γεγονός*.
\begin{align*}
S &= \{s_1,s_2,\cdots,s_n\}\\
S^{*} &= \{\emptyset,\{s_1\},\{s_2\}\cdots,\{s_n\}\\,& \{s_1,s_2\} \{s_1,s_3\} \cdots \{s_{n-1},s_{n}\}\cdots \}\\
\end{align*}

Ο παραπάνω τύπος προκύπτει μαθηματικά από το:
#+begin_theorem
*Διώνυμο του Newton*:
\begin{align*}
(a+b)^n=\sum^n_{l=0} (\binom{n}{k})a^lb^{n-l} = \cdots\\
\end{align*}
#+end_theorem

#+begin_comment
(Ακολουθεί ένας εντελώς παιδιαστικός τρόπος εξήγησης του διωνύμου του Newton):
#+end_comment

Σε ένα βιβλίο του Σέρλοκ τίθεται ο γρίφος του πόσα μηνύματα μπορεί να περάσει
ένα σύστημα γεμάτων-ή-άδειων /κύκλων/. Πρόκειται για συσκευές που είχαν ανα
κάποια χιλιόμετρα με σκοπό να μεταδίδουν μηνύματα γρήγορα;
Αρχίζουμε από την πρώτη τρύπα:
1. Η τρύπα έχει δύο καταστάσεις (ανοιχτή/κλειστή), επομένως για κάθε πιθανό
   συνδυασμό που έχει προκύψει από τις προηγούμενες /μελέτες/ έχουμε δύο πιθανές
   συνέχειες.
2. Πολλαπλασιάζουμε λοιπόν όλες τις ήδη υπάρχουσες καταστάσεις επί του δύο (
   εκτός αν ήμαστε στην πρώτη τρύπα οπότε θέτουμε τις καταστάσεις σε 2 )


** Πράξεις γεγονότων.
Για $A,B$ γεγονότα του $S$
- *Ισότητα:*  $A=B$
  Ίδια δειγματοσημεία
- *Ξένα/Ασυμβίβαστα:* $A\cap B$
  Αν η τομή του δειγματοχώρου τους έιναι το μηδενικό σύνολο
- *Συμπλήρωμα:* $\bar{A}$
  Όλα τα σημεία του $S\notin A$
- *Ένωση:* $A\cup B$
  Ολα τα σημεία ανήκουν ή στο A _ή_ στο $B$
- *Τομή:* $A\cap B$
  Που ανήκουν και στα δύο ( προφανώς )
- *Διαφορά:* $A-B = A\cap \bar{B}$
  Που ανήκουν στο ένα και όχι στο άλλο

Οι πράξεις αυτές μπορούν εύκολα να γίνουν εικόνες με την χρήση διαγραμμάτων Venn.

*** De Morgan: αρχή του δυισμού
\begin{align}
\bar{(A\cap B)} = \bar{A}\cup \bar{B}\\
\bar{A\cup B} = \bar{A}\cap \bar{B}
\end{align}

#+begin_comment
Μνημονικός Κανόνας: το συμπληρωματικό πάει στο κάθε επι μέρους στοιχείο και η
ένωση γίνεται τομή ( όπως και αντίστροφα )
#+end_comment

*** Παράδειγμα
Βάση των προηγουμένων, με άλγεβρα γεγονότων, να γραφούν τα παρακάτω
1. Τουλάχιστον ένα από τα $A,B,C$
   $P = A \cup B \cup C$
2. Μόνο ένα από τα $A,B,C$
   $P = A\cup B \cup C - A\cap B - A\cap C - B\cap C$
3. Μόνο δύο από τα $A,B,C$
   $P = \cdots$

* Θεωρία πιθανοτήτων
Μερικά εισαγωγικά παραδείγματα, τα οποία δείχνουν πως η /λογική/ κάτω από
ορισμένες συνθήκες μας κάνει να μην καταλαβαίνουμε τις πραγματικές πιθανότητες
να συμβεί κάποιο γεγονός.

*** Γενέθλια την ίδια μέρα
Έστω ότι σε ένα δωμάτιο βρίσκονται $n$ άτομα. Τι τιμή πρέπει να λάβει το $n$
έτσι ώστε:
- Να είναι σίγουρο ότι δύο άτομα έχουν γενέθλια την ίδια μέρα; $n\geq 365$
- Να είναι πιο πιθανό να έχουν την ίδια μέρα γενέθλια δύο άτομα  απο ότι να μην
  έχουν; $n \geq 23$

*** Ρίψη Νομίσματος

*** Διάρκεια καλής λειτουργίας λαμπτηρα
*** Ελαττωματικά τεμάχια
\begin{equation}
S = \{0,1,2,\cdots\}
\end{equation}
*** Διάρκεια καλής λειτουργίας λαμπτήρα
\begin{equation}
S = \{x| x\in \mathbb{R} \}
\end{equation}
*** Αριθμός σωματιδίων σε ραδιενεργό σώμα

* Counting - Απαρίθμηση
Γενικά ένας εύκολος τρόπος με τον οποίο μπορεί κανείς να σχηματίσει έναν /νοητό/
χάρτη για τις πιθανές τελικές καταστάσεις είναι τα δενδροδιαγράμματα: (tree diagrams)

Παρόλα αυτά, δεν είναι πάντοτε αρκετά περιορισμένος ο αριθμός των γεγονότων ώστε
να συμφέρει η ανάλυση τους με κάποιον από τους /εύκολους/ τρόπους που είδαμε
μέχρι στιγμής. Καθώς τα νούμερα αυξάνονται είναι παράλογο να παραμείνουμε σε
τόσο /χειρωνακτικές λύσεις/.

** Θεώρημα πολλαπλασιαστικού κανόνα για γεγονότα
/Είναι ακόμα πιο εύκολο κατανοητό με την λογική παρά μέσα από την έκφραση/
Εχουμε ένα πρώτο πείραμα με $n_1$ δυνατά αποτελέσματα, και για κάθε ένα από τα
αποτελέσματα του πρώτου πειράματος έχουμε $n_2$ δυνατά αποτελέσματα του δεύτερου
πειράματος κτλ, και για κάθε ένα από τα αποτελέσματα του $k − 1$ πειράματος έχουμε
nk δυνατά αποτελέσματα του τελευταίου $k$ πειράματος, τότε όλα τα δυνατά
αποτελέσματα από όλα τα πειράματα είναι $n1 · n2 · · · nk$

*** Παραδείγματα και χρήσεις
1. Με πόσους τρόπους μπορούν να εκλεγούν ο πρόεδρος και ο αντιπρόεδρος σε έναν σύλλογο 25 ατόμων; $25*24$

   /Επεξήγηση:/ Έχουμε μια περίπτωση στην οποία μας ενδιαφέρει η διάταξη (
   δηλαδή έχει διαφορά το ποιος θα βγει πρόεδρος και ποιος αντιπρόεδρος -
   γίνεται να βγουν τα ίδια άτομα αλλά με διαφορετική διάταξη μα είναι και πάλι
   έγκυρο γεγονός ). Έχουμε 25 άτομα που μπορούν να βγούν πρόεδρος, όμως με το
   που βγαίνει κάποιο από αυτά πρόεδρος μόνο 24 μένουν για να καλύψουν την θέση
   του αντιπροέδρου. Δεν γίνεται να είναι κανείς και τα δύο (/κοιτάζει παράξενα
   στα απολυταρχικά καθεστώτα/[fn:1])

2. ́Ενα τεστ αποτελείται από 12 ερωτήσεις σωστού - λάθους. Με πόσους
   διαφορετικούς τρόπους μπορεί να απαντήσει ο φοιτητής; $2^{12}$[fn:3]


** Θεώρημα για τον αριθμό αντιμεταθέσεων $k$ απο $n$ στοιχείων
/Αντιμετάθεση, γνωστή στους περισσότερους από τον αγγλικό όρο: permutation/

Το πλήθος των αντιμεταθέσεων $k$ στοιχείων από ένα σύνολο $n$ στοιχείων είναι:
\begin{equation}
_np_k= n(n-1)(n-2)\cdots(n-k+1) = \frac{n!}{(n-k)!}
\end{equation}

** Θεώρημα για τον αριθμό συνδυασμών $k$ εκ $n$ στοιχείων

\begin{equation}
_nc_k = \binom{n}{k} = \frac{n!}{k!(n-k)!}
\end{equation}

*** Παρατήρηση
Από τον παραπάνω τύπο πολύ εύκολα προκύπτει πως:
\begin{equation}
\binom{n}{k}=\binom{n}{n-k}
\end{equation}

* footnotes

[fn:3] Η παιδιαστική εξήγηση του Σέρλοκ ταιριάζει γάντι και εδώ.
[fn:1] I'm sorry
