title: "Simple Man's Journey"
description: "Personal Blog"
copyright: "Copyright: Lamprinos Chatziioannou and Michael Rose"

locale: "el-GR"
timezone: Europoe/Athens
date_format: "%Y-%m-%d"
remote_theme: "mmistakes/so-simple-theme"

url: "https://chatziiola.github.io"
source: .
destination: ./_site

search: true
comments: false
read_time: false
future: true
mathjax: true
permalink: date
highlighter: rouge
markdown: kramdown

author:
    name: "Lamprinos Chatziioannou"
    email: "chatziiol@gmail.com"
    picture: 
    twitter: "@chatziiola"
    links:
        - title: GitHub
          url: https://github.com/chatziiola
          icon: fab fa-github
        - title: Twitter
          url: https://twitter.com/chatziiola
          icon: fab fa-twitter-square
        - title: Instagram
          url: https://instagram.com/oxi_esy_lampeis_mpampi_mou
          icon: fab fa-instagram
       # - title: LinkedIn
       #   url: 
       #   icon: fab fa-linkedin
       # - title: StackExchange
       #   url: 
       #  icon: fab fa-stack-exchange
       
footer_links:
        - title: GitHub
          url: https://github.com/chatziiola
          icon: fab fa-github
        - title: Twitter
          url: https://twitter.com/chatziiola
          icon: fab fa-twitter-square
        - title: Instagram
          url: https://instagram.com/oxi_esy_lampeis_mpampi_mou
          icon: fab fa-instagram
   
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
