author: Lamprinos Chatziioannou
title: Dazed and Confused
description: A nerd's takes on stuff
theme: no-style-please
email: chatziiol@gmail.com
baseurl: ""
#permalink

theme_config:
	appearance: "auto"
	back_home_text: ".."
	date_format: "%Y-%m-%d"
	show_description: false

sass:
	style: :compressed

plugins:
 - jekyll-feed
 - jekyll-seo-tag
