# Welcome to Jekyll!
#
# Site settings
title: An Educated Fool
email: chatziiol@gmail.com
description: >
 A nerds takes on stuff
baseurl: "" 
url: "https://chatziiola.github.io"

# Build settings
markdown: kramdown
theme: no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
