title: "Simple Man's Journey"
description: "Personal Blog"
copyright: "©Copyright 2020, Lamprinos Chatziioannou and Michael Rose.<br/>This work is licensed under a Creative Commons Attribution 4.0 International License (not the software). Share generously, but provide attribution <br/>  Operated with love and humour."
# TODO -> custom skin (differentiation from the rather basic one found here)
skin: "/assets/css/skins/light.css"

locale: "gr-GR"
timezone: Europe/Athens
date_format: "%d-%m-%Y"
remote_theme: "mmistakes/so-simple-theme"

url: "https://chatziiola.github.io"
source: .
destination: ./_site
# TODO -> add logo
# site.logo: 

search: true
future: true
# To be able to press on category links
category_archive_path: "/categories/#"                      
mathjax: false
# TODO -> see if you can find well designed comment provider and consider enabling read_time
read_time: true
words_per_minute: 200
comments: false
# not installing disqus due to ads and bad-looking ui
#disqus:
#   shortname: lamprinoschatziioannou

permalink: date
highlighter: rouge
markdown: GFM

author:
    name: "Lamprinos Chatziioannou"
    email: "chatziiol@gmail.com"
    picture: "images/author.png"
    twitter: "@chatziiola"
    links:
        - title: GitHub
          url: https://github.com/chatziiola
          icon: fab fa-github
        - title: Twitter
          url: https://twitter.com/chatziiola
          icon: fab fa-twitter-square
        - title: Instagram
          url: https://instagram.com/oxi_esy_lampeis_mpampi_mou
          icon: fab fa-instagram
        - title: Dev.to
          url: https://dev.to/chatziiola
          icon: fab fa-dev
       # - title: LinkedIn
       #   url: 
       #   icon: fab fa-linkedin
       # - title: StackExchange
       #   url: 
       #  icon: fab fa-stack-exchange
       
footer_links:
        - title: GitHub
          url: https://github.com/chatziiola
          icon: fab fa-github
        - title: Twitter
          url: https://twitter.com/chatziiola
          icon: fab fa-twitter-square
        - title: Instagram
          url: https://instagram.com/oxi_esy_lampeis_mpampi_mou
          icon: fab fa-instagram
        - title: Dev.to
          url: https://dev.to/chatziiola
          icon: fab fa-dev
   
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
