title: "Simple Man's Journey"
description: "Personal Blog on Informatics"

url: "https://chatziiola.github.io"
source: .
destination: ./_site

locale: "en-US"
timezone: Europe/Athens
date_format: "%d-%m-%Y"

skin: "/assets/css/skins/light.css"
logo: "/images/site-logo.png"
remote_theme: "mmistakes/so-simple-theme"

search: true
future: true
category_archive_path: "/categories/#"                      
mathjax: false
# TODO -> aesthetically appealing comment section
read_time: false
words_per_minute: 200
comments: false

permalink: date
highlighter: rouge
markdown: GFM

collections:
    greek:
          output: true
          permalink: /:collection/:path/

defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      
feed:
  path: atom.xml

author:
    name: "Lamprinos Chatziioannou"
    email: "lampischatziioannou@gmail.com"
    picture: "images/author.png"
    links:
        - title: GitHub
          url: https://github.com/chatziiola
          icon: fab fa-github
        - title: Twitter
          url: https://twitter.com/chatziiola
          icon: fab fa-twitter-square
        - title: Instagram
          url: https://instagram.com/chatziio.zs
          icon: fab fa-instagram
        - title: Dev.to
          url: https://dev.to/chatziiola
          icon: fab fa-dev
        - title: Feed
          url: atom.xml
          icon: fas fa-rss-square
       
   
google_fonts:
  - name: "Source Sans Pro"
    weights: "300,300i,700,700i"
  - name: "Lora"
    weights: "300,300i,700,700i"

plugins:
    - jekyll-seo-tag
    - jekyll-feed
