#+TITLE: Blog posts: A means towards freedom 
#+DATE_STARTED: <2022-08-24 19:38>
#+DATE: <2023-10-18 Wed>
#+DESCRIPTION: Inspired by JRE #1386, with Ryan Holiday
#+FILETAGS: :joerogan:ryanholiday:

#+begin_note
This article started as a draft more than a year ago, yet I felt that
it was worth publishing. Forgive me if the interview is too old :P
#+end_note

Everybody knows the feeling of having had enough of something;
/something/ may mean so many different things and is slightly different
for anyone, due to our wide-ranging interests, but for me it is a
common consequence of pushing myself to learn stuff, so broad in
nature that their components are still unclear. That's how I felt when
I stopped studying for my electronics examination and sat on the
couch, checking for low effort tasks I could tackle to clear my mind.

In the meantime, I put a podcast I started too long ago, but never
finished: [[https://open.spotify.com/episode/3VbGyix7GOozgg8sry2Tmr?si=131234b98ae940ce][The Joe Rogan Experience: #13836, with Ryan Holiday]]. Ryan's
book /The Daily Stoic/ inspired my to read Marcus Aurelius' /Meditations/
and to start developing some of my philosophical views and ideas in my
Digital Zettelkasten - though I have since abandoned that practice:
it feels very fake and mainstream, with diminishing returns; I would
rather just think of these /principles/. As far as the book is
concerned, however, I found it intriguing and practical.

That is the reason why I felt disappointed by the author's quick
dismissal of blog posts as a /weak medium/. While it is true that a huge
percentage of the blog posts online (such as mine) are mediocre, there
are so many eloquent, carefully written and impressively extensive
articles on so many different subjects, that ... I feel saddened.

That's why I decided to write a small piece on it.

* Over-exposure 

The problem, if such exists, with blog posts is none other than the
overproduction of blog posts. This is not unique by any means to the
blog posts, as one can easily understand, nowadays. There are too many
books getting published everyday, too many movies getting produces,
too many series, too many of everything. But there is nothing wrong
with that; while some of it might not meet one's quality standards,
they might be someone else's ideal way to spend their time, and at the
end of the day, that's what matters.

* TODO Not all mediums are the same

Before criticizing something one should understand the context around
it, and embrace what it has to offer. Blog posts may be inherently
limited in length (although there is no actual limitation), but they
might be the only written form of publishing that has the potential of
tremendously quick feedback and interaction between the author and the
readers; all of that because of the integration of technology in
articles[fn:1] . 


* The medium does not make the content

While I agree that other forms of writing (sticking to that to avoid
getting too broad), are usually (and I would assume by a significant
percentage) of higher quality, as a result of a team of *professionals*
working on them, there is nothing inherently of /low quality/ in blog
posts. If you spend some time online you will definitely know that
this is the case. This phrase completely highlights what I try to
express in this paragraph:

#+begin_quote
Just like an article in a newspaper or a magazine is not guaranteed to
be of a certain quality, potentially turning out completely pointless
or under different circumstances, so good that it deserves a Pulitzer
prize, a blog post might be just the same.
#+end_quote

* TODO On the faulty usage of it

* TODO On its effect on the writer

* TODO On the inherent equality

* Footnotes

[fn:1] This is not the ideal way to explain it, but if you think of
it, as expressed in the next section as well, blog posts are nothing
but logical TODO 
