#+TITLE: Blog posts: A means towards freedom 
#+DATE: <2022-08-24 19:38>
#+DESCRIPTION: Inspired by JRE #1386, with Ryan Holiday
#+FILETAGS: :joerogan:ryanholiday:

- [] Find the quote where they talk about blog posts 
  #+begin_quote
  #+end_quote

Everybody knows the feeling of having enough of something; it may be slightly
different for anyone experiencing it, due to our wide-ranging interests, but for
me it is a common result of pushing myself to learn stuff, whose components are
still unclear. That's how I felt when I stopped studying for my electronics
examination and sat on the couch, checking for low effort tasks I could tackle
to clear my mind.

In the meantime, I put a podcast I started too long ago, but never finished: [[https://open.spotify.com/episode/3VbGyix7GOozgg8sry2Tmr?si=131234b98ae940ce][The
Joe Rogan Experience: #13836, with Ryan Holiday]]. Ryan's book
/The Daily Stoic/ (one of the rare gems I found wasting my time in Instagram)
inspired my to read Marcus Aurelius' /Meditations/ and to start developing some of
my philosophical views and ideas in my Digital Zettelkasten. I am not going to
lie: I liked that book, a lot. ( And I'm still reading it, daily )

That is the reason why I felt disappointed by the author's quick dismissal of
blog posts as a /weak medium/. While it is true that a huge percentage of the blog
posts online are mediocre ( my posts presumably belong here as well - I'm
actively working to change that ), there are so many eloquent, carefully written
and impressively extensive articles on so many different subjects, that ...

* ACTION On the quality of blog posts
* ACTION On their lack of quality
* ACTION On the ethics and ideas behind the medium
* ACTION On the faulty usage of it

