:PROPERTIES:
:ID: lec-SSD-third-boring
:END:
#+TITLE: Διάλεξη 3: Κυρίως Ασκήσεις.
#+FILETAGS: lecture
#+DATE: <2022-10-12>
#+FILETAGS: lecture
#+COURSE: SSD
#+INSTITUTION: A.U.Th

#+begin_comment
Αρχίζω να αναθεωρώ την αρίθμηση στις διαλέξεις για αυτό το μάθημα. Πρέπει να
έχασα μια την προηγούμενη Τετάρτη αν και δεν με ήταν εμφανές.
#+end_comment

* Συνέχεια επί τυχαίων μεταβλητών.
** Οι συναρτήσεις τμ αποτελούν και οι ίδιες με την σειρά τους τμ.
\begin{equation}
\label{eq:1}
y = g(x)
\end{equation}
όπου $X,Y$ τυχαίες μεταβλητές.

Αν η $g$ 1-1 ως προς $x$ τότε, όταν αναζητούμε πιθανότητες της μορφής:
\begin{equation}
\label{eq:2}
Pr\{ Y = y_k \} \stackrel{g(x_k) = y_k}{=} Pr\{ X = x_k\}
\end{equation}

Προφανώς, όμως, αυτό δεν ισχύει υπό όλες τις συνθήκες, και δεν ειναι κάτι που
μπορούμε πάντα να γνωρίζουμε. Ο γενικός κανόνας:
\begin{equation}
\label{eq:3}
Pr\{ Y = y_k \} \stackrel{y_k = g(x_i),  i\in \cdots}{=} \sum_{i=1} Pr\{ X = x_i \}
\end{equation}

**** Παρατηρήσεις:
- Για τα παραπάνω είναι χρήσιμη η γραφική παράσταση αν δίνεται. Προσοχή η μορφή
  της γραφικής παράστασης της /εξαρτώμενης/ τυχαίας μεταβλητής δεν είναι
  απαραίτητο πως θα μοιάζει με εκείνη της /ανεξάρτητης/

*** Βρίσκοντας την τιμή της ΣΠΠ /σύνθετης/ συνάρτησης :methodology:
#+begin_comment
Το σύνθετη δεν είναι εδώ ως ενδεικτικό της δυσκολής, αλλά σαν /πλεγμένη/
#+end_comment

Δοθείσης πλεγμένης έκφρασης με τις τμ $X,Y$. Μπορούμε να βρούμε την $f_Y(y)$ ως
εξής:
1. Λύνουμε την $y = g(x)$
2. Έχουμε, έτσι, $y = g(x_i) \forall i$ τέτοια ώστε $x_i \in {\mathbb R}$
3.
\begin{equation}
\label{eq:4}
f_Y(y) = \sum_{i=1}
\frac{f_x(x_i)}{|g'(x_i)|}
\end{equation}


* Παραδείγματα
Η διάλεξη είχε κυρίως ασκήσεις: Λύθηκαν τα παραδείγματα των διαφανειών 34 και 35
καθώς και η άσκηση με την δίοδο Zener επί της διαφάνειας 36 την οποία αν
/διορθώσω/ θα ανεβάσω εδώ.

