#+TITLE: Διάλεξη 2: Τυχαίες μεταβλητές
#+FILETAGS: lecture
#+DATE: <2022-10-10>
#+FILETAGS: lecture
#+COURSE: SSD
#+INSTITUTION: A.U.Th

* Τυχαίες μεταβλητές
Μετάβαση από τα αορίστως ορισμένα γεγονότα σε καλύτερα ορισμένα.

Δόθηκε ιδιαίτερη έμφαση στο /να θυμάται κανείς ότι η τιμή της τμ δεν είναι
αριθμός αλλά σύνολο γεγονότων/

** Τύποι
Κλασσικά:
1. Συνεχείς (παράδειγμα: γωνία στον τροχό της τύχης)
2. Διακριτές (παράδειγμα: ... κορώνα γράμματα)
3. Μεικτού τύπου

* Συνάρτηση Κατανομής πιθανότητας (CDF)
#+begin_comment
Έτσι όπως παρουσιαστηκε θα νόμιζε κανείς ότι είναι: Η τυπική ΑΣΚ που είδαμε σε
PTS.  Παρόλα αυτά, θεωρώ πως απλά φάνηκε έτσι επειδή θεώρησε σαν γεγονός το $\{X<x_0 \}$

Και πάλι, θεωρώ πιθανό το να κάνω λάθος.
#+end_comment

** Κλιμακωτή συνάρτηση κατανομής
Όταν βλέπεις κλιμακωτή συνάρτηση κατανομής γνωρίζεις πως εκείνη σχετίζεται με
διακριτή τμ.

** Ιδιότητες συν καταν
Οι κλασσικές ιδιότητες της ΑΣΚ:
\begin{align*}
F_X(-\infty) &= 0\\
F_X(\infty) &= 1\\
\end{align*}
ενώ ακόμα:
- η $F_X$ αύξουσα
- Συνεχής εκ δεξιών
- $1-F_X$, συχνά ορισμένη ως *συμπληρωματική* (complementary) συνάρτηση της $F_X$,
  και συμβολίζεται ως $F^{C}_X$

** Προσεγγίζοντας την πιθανότητα σε σημείο
Αυτό είναι για όταν μπλέκουμε με την πιθανότητα:
\begin{equation}
\label{eq:1}
Pr\{ x_1 \leq X \leq x_2 \}
\end{equation}

Υπο αυτές τις συνθήκες, γνωρίζοντας ήδη από την ΑΣΚ:
$Pr\{\cdots\} = F(x_2) - F(x_1)$:

Έχουμε: $x_2= x, x_1 = x-\epsilon, \epsilon\to0$, εκ του οποίου:
\begin{equation}
\label{eq:2}
Pr\{\cdots\} = F(x) - F(x^{-})
\end{equation}
Όπου προφανώς $x^-$ είναι η εκ δεξιάς προσέγγιση του $x$

Με βάση την $F_x$, ακόμα μπορούμε να διακρίνουμε τις τμ.
- $F_X$ συνεχής, τότε η τμ συνεχούς τύπου
- $F_X$ κλιμακωτή, τότε η τμ διακριτού τύπου
- $F_X$ συνδυασμός των παραπάνω, τότε η τμ μεικτού τύπου


Στην περίπτωση, λοιπόν, της συνεχούς (τουλάχιστον στα εμπλεκόμενα σημεία) τμ,
η πιθανότητα ισούται με το 0. Δεν υπάρχει ασυνέχεια, ούτε και ουσιαστική
πιθανότητα να συμβεί ένα εκ των απείρων γεγονότων.

Αυτό, όμως, αλλάζει όταν έχουμε ασυνέχεια. Ισχύει δηλαδή πως *αυτή η πιθανότητα
  είναι ίση με το πλάτος της ασυνέχειας που παρουσιάζεται σε εκείνο το σημείο*

** Παραδείγματα.
Λύθηκαν, από τις διαφάνειες, μερικά απλά παραδείγματα ( για αυτό και δεν
σημειώθηκαν ).

*** Παράδειγμα /εξέτασης για ΑΣΚ/
- Σε αυτό το παράδειγμα, η συνάρτηση δεν ήταν ΑΣΚ καθώς δεν ήταν συνεχής απο
  δεξιά. (Το μόνο που κάνεις είναι: ελέγχεις τις ιδιότητες)

*** Παράδειγμα με /ράμπα/

* Συνάρτηση πυκνότητας πιθανότητας (PDF)
Εφεξής ΣΠΠ.

Ορίζεται, κατά τον Νέστορα, βάση της ΑΣΚ:
\begin{equation}
\label{eq:3}
f_X = \frac{dF_X}{dt}
\end{equation}

Και οι ιδιότητες της είναι οι κλασσικές:
\begin{align*}
f_X(x) &\geq 0, \forall x\\
\int_{-\infty}^{\infty}f_Xdx &= 1\\
F_X &= \int_{\infty}^tf_Xdx\\
Pr\{x_1 < X \leq x_2\} &= \int_{x^{+}_1}^{x^{ +}_2}f(x)dx\\
Pr\{x_1 \leq X \leq x_2\} &= \int_{x^{-}_1}^{x^{ +}_2}f(x)dx\\
\end{align*}

* Μορφή συναρτήσεων ΔΤΜ
Προφανώς ΔΤΜ: Διακριτή τυχαία μεταβλητή.

Όπως είπαμε προηγουμένως [[*Κλιμακωτή συνάρτηση κατανομής][στην κλιμακωτή συνάρτηση κατανομής]], όταν δουλεύουμε
με ΑΣΚ η γραφική παράσταση της $F_X$ διακριτής τμ είναι κλιμακωτή, ενώ
(χτίζοντας επί εκείνου) η ΣΜΠ (/συνάρτηση μάζας πιθανότητας/ - pmf) έχει την
μορφή αθροίσματος συναρτήσεων $\delta$ (δέλτα)
  
Ισχύει δηλαδή
\begin{equation}
\label{eq:4}
f_X(x) = \sum_{i=1}^np_i\delta(x-x_i)
\end{equation}

* Δεσμευμένες πιθανότητες ( Πιθανότητες υπό συνθήκη )
\begin{equation}
\label{eq:5}
Pr\{X\leq x | B\} = \frac{Pr\{X\leq x,B\}}{Pr\{B\}}
\end{equation}

Συμβολίζουμε τις ΑΣΚ και ΣΠΠ των δεσμευμένων, έτσι, πιθανοτήτων ως εξής:
- ΑΣΚ: $F_{X|A}$
- ΣΠΠ: $f_{X|A}$

Ακόμα έχουμε:
Αν το γεγονός $A=\{X\leq \alpha\}$

\begin{align}
\label{eq:6}
F_{X|A} =& 
\begin{cases}
1 & x\geq \alpha\\
\frac{Pr\{X\leq x\}}{Pr\{X\leq \alpha\}} & x\geq \alpha\\
\end{cases} \\
f_{X|A} =& 
\begin{cases}
1 & x\geq \alpha\\
\frac{Pr\{X\leq x\}}{Pr\{X\leq \alpha\}} & x\geq \alpha\\
\end{cases} 
\end{align}

#+begin_comment
Αυτά εδώ, αν και φαίνονται λίγο /δύσκολοι/ σαν τύποι, βγαίνουν πολύ εύκολα στο
χαρτί. Χρήσιμα για αυτό είναι:
#+end_comment
\begin{align*}
\label{eq:9}
f_x &= \frac{d{F_X}}{d{x}}\\
F_X(\alpha) &= \int_{-\infty}^{\alpha} f_xdx
\end{align*}

** Χτίζοντας πιο σύνθετες πιθανότητες
Αν, πάλι, το $B=\{a < X \leq b\}$
έχουμε:
\begin{equation}
\label{eq:7}
F_{X|B}(x) = \frac{Pr\{X\leq x, a< X \leq b\}}{Pr\{ a < X \leq b\}}
\end{equation}

το οποίο μπορούμε να το αναλύσουμε με τις εξής συνθήκες:
- $x\leq a$
- $x\geq b$
- $x\in (a,b)$

Έτσι καταλήγουμε:
\begin{equation}
\label{eq:10}
F_{X|B}(x) =
\begin{cases}
0 & x\leq a\\
1 & x\geq b\\
\frac{F_X(x) - F_X(\alpha)}{F_X(b) - F_X(\alpha)} & x\leq a
\end{cases}
\end{equation}

Οι πρώτες δύο σχέσεις είναι αυτονόητες, ενώ η τρίτη προκύπτει από το γεγονός οτι
για $x\in (\alpha,b)$, $Pr\{X\leq x, \alpha < X\leq b\}$ γίνεται $Pr\{\alpha< X\leq x\}$
