#+TITLE: Διάλεξη: 1 Εισαγωγικά
#+FILETAGS: lecture
#+DATE: <2022-10-03>
#+FILETAGS: lecture
#+COURSE: SSD
#+INSTITUTION: A.U.Th
#+AUTHOR: Λαμπρινός Χατζηιωάννου
#+LATEX_CLASS_OPTIONS: [a4paper,11pt,titlepage]
#+LANGUAGE: el


* Ανασκόπηση
Στο μάθημα των Σημάτων Συστημάτων εξετάστηκαν:
-  Νομοτελειακά συστήματα
-  Μετασχηματισμοί Fourier και  Laplace
-  Είσοδος έξοδος γραμμικού και χρονοαμετάβλητου συστήμ.

** Τύποι:
- Οι γνωστοι τύποι, δεν τους έγραψα γιατί με φάνηκαν υπερβολικά γνωστοί:
- Έγραψα μόνο την συνέλιξη, σαν παράδειγμα τέτοιου τύπου:
\begin{align}
\label{eq:1}
y(t) = x(t) * h(t) = \int_{-\infty}^{\infty}x(\tau)h(t-\tau)d\tau
\end{align}


* Στοχαστικό σήμα
Στα στοχαστικά σήματα έχουμε την μετάβαση από τις αυστηρές μαθηματικές εκφράσεις
στις πιθανότητες και στην έκφραση του σήματος με την χρήση πιθανοτήτων και
ιδιοτήτων πιθανοτήτων

#+begin_definition Στοχαστικό σήμα
Σήμα για το οποίο δεν υφίσταται νομοτελειακή (κλειστή) έκφραση για την περιγραφή του.
#+end_definition

Ουσιαστικά πρόκειται για σήμα που επηρεάζεται από διάφορους χρονικά μεταβλητούς
  και αγνώστης φύσεως παράγοντες με αποτέλεσμα να μην μπορούμε να βγάλουμε
  /απόλυτη/ έκφραση.
  
** Παραδείγματα στοχαστικών σημάτων
- Σήμα που λαμβάνεται στον δεκτη ενός τηλεπ συστήματος.
  - Είναι στοχαστικό λόγω του θορύβου. Δεν είναι δυνατόν να προσδιοριστεί
    επακριβώς ( παρα μόνο στις συνθήκες του απόλυτου μηδενός που δεν μας
    ενδιαφέρουν ). Αυτό συμβαίνει καθώς προκαλείται από την κίνηση ηλεκτρονίων.
- Έξοδος μικροφώνου
  - Πάλι πολλοί τέτοιοι παράγοντες, είναι αδύνατο να προσδιορίσεις σε ενιαίο
    τύπο την φωνή του ομιλητή ποσο μάλλον όταν σε αυτή εμπλέκεται και ο θόρυβος
    του μικροφώνου /( πιθανά αμφισβητήσιμη ερμηνεία )/
- Είσοδος έξοδος πελατών σε ουρά αναμονής
  - *Θεωρία ουρών αναμονής*
  - Εφαρμόσιμη σε *δίκτυα*.
- τιμή μετοχής σε χρονική περίοδο
- Αριθμός ηλεκτρονίων σε φωτοδίοδο.

* Προσέγγιση του μαθήματος
Το πρώτο κομμάτι του μαθήματος είναι /αποκλειστικά/ επανάληψη στην θεωρία
πιθανοτήτων και αργότερα επέκταση με μερικές έννοιες που δεν εξετάστηκαν εκεί,
πριν προχωρήσουμε στην ανάλυση, στοχαστικών σημάτων.

* Θεωρία Πιθανοτήτων
Οπότε ναι... Έχουμε αυτά εδώ:
- [ ] Θεωρία Συνόλων...
  - [ ] ιδιοτητες ...

** Πιθανοτικό μοντέλο
Πείραμα -> Δειγμ χώρος -> Κανόνας πιθαν.

** Ορισμοί πιθανότητας
*** Laplacian
#+begin_comment
(Δεν ήξερα οτι συνδέεται και με αυτό ο Laplace):
#+end_comment
    \begin{equation}
    \label{eq:2}
    P\{A\} = \frac{N_A}{N}
    \end{equation}
    όπου $N_A$ το πλήθος των γεγονότων του $A$ και $N$ το πλήθος στοιχείων του δειγματοχώρου.
    - Δεν χρειάζεται να εκτελέσω το πείραμα ούτε μια φορά.

*** Σχετικής συχνότητας
\begin{equation}
\label{eq:3}
P\{A\} = \lim_{N\to \infty}\frac{N_A}{N}
\end{equation}
- Προϋποθέτει τόσο την ύπαρξη του ορίου όσο και την εκτέλεση του πειράματος
  άπειρες (επαρκώς πολλές) φορές.

*** Αξιωματικός
Αυτός είναι ο πιο /μαθηματικός/ ορισμός: Βλέπε τα τρία βασικά αξιώματα θεωρίας
πιθανοτήτων: Θεωρήματα Kolmogorov.

*** Πιθανοτικός χώρος πραγματικών αριθμών.
Πρακτικά AΣΚ, ΣΠΠ όπως τις συναντήσαμε στις πιθανότητες.
