#+TITLE: Διάλεξη: Σήματα και διανύσματα (?)
#+FILETAGS: lecture
#+DATE: <2023-03-06>
#+COURSE: TLP2
#+INSTITUTION: A.U.Th

- Αναπαράσταση σημάτων ως διανυσμάτων με την αντιστοίχιση τους (κάπου 1960ς)
  - από τους Jacobs, Wozencraft

- Προφανής σύνδεση με διανυσματική άλγεβρα και βάσεις του συστήματος για
  καλύτερη κατανόηση και /εικονοποίηση/ των όσων λέγονται.
    
- Και πως αυτό ουσιαστικά εξελίσσεται στην /δημιουργία/ αστερισμών.
  - Αστερισμοί: συνοπτικά σύνολο σημάτων/διανυσμάτων
  - Οι δύο έννοιες σημάτων και διανυσμάτων θεωρούνται απολύτως /όμοιες/ εδώ.

* Επανάληψη επί της αλγεβρικής θεωρίας
- Cauchy/Schwarz
- Μέτρα
- Ανεξαρτητοποίηση
- Ορθογωνοποίηση Gram-Schmidt.
  - Δες 18.06

* Σήματα και διανύσματα - μια αναλογία (και γενικότερη επανάλψη στα σήματα.)
- Σύνολο πράξεων
- Θεμελιώδη σήματα/διανύσματα -> βάσεις
- Γραμμική ανεξαρτησία και κατάλληλες πράξεις σε σήματα/διανύσματα.

Συνέχισαν οι κατάλληλοι ορισμοί των διανυσματικών πράξεων (νορμα και εσωτερικό
γινόμενο) σε σήματα.

- Συσχέτιση, προβολή, ορθογωνικότητα, ευκλείδεια απόσταση.

* Αστερισμοί - Constellations
- Κάθε σήμα ένα σημείο
- Μέση ενέργεια:
  
\begin{equation}
\label{eq:1}
\textsl{E}_s = \sum_{i=1}^M ||s_i||^2 Pr(s_i)
\end{equation}

μας ενδιαφέρει γιατί ουσιαστικά ταυτίζεται με την μέση κατανάλωση ενέργειας όταν
αναφερόμαστε σε χρήση του εκάστοτε αστερισμού.


#+begin_example
- Διαφάνεια 23.
- Η μόνη ερώτηση που θα έκανα εκεί θα ήταν περί της κανονικότητας των βάσεων, καθώς θα μας οφελούσε πολύ να είχαμε πάρει σαν βάσεις μόνο τα:
- $A\cos{\left(2\pi f_ct\right)}$ αντί να έχουμε και τις ρίζες.
#+end_example


** Απόσταση, Ενέργεια και Πιθανότητα Σφάλματος.
Απόσταση από την αρχή των αξόνων συνεπάγεται μεγαλύτερη η μικρότερη ενέργεια και
εξ' αυτού υψηλότερη κατανάλωση.

Την ίδια στιγμή εξαιρετικά μικρότερη κατανάλωση συνεπάγεται μεγαλύτερη
πιθανότητα σφάλματος.

Συνεδεμένο με αυτό το *SPHERE PACING*. Δες μάλλον βιβλιογραφία ως προς αυτό.
Κλασσικά συνδέεται με Shannon.

** Παραδείγματα αστερισμών:
*** APSK:
Amplitude Phase Shift Keying
#+begin_note
Συνοπτικά πρόκειται για σύνολο ομοαξονικών κύκλων σταθερής ενέργειας και
διαμοιρασμός των διακριτών σημάτων σε αυτούς τους κύκλους.
#+end_note

- APSK: 16-2 (16 είναι το πλήθος των στοιχείων και το 2 είναι το πλήθος των
  ενεργειακών σταθμών που υπάρχουν στον αστερισμό)
- Με το ίδιο παράδειγμα στο 16-4 APSK τα 16 σήματα είναι διανεμημένα σε 4
  /ομο-ενεργειακούς/ κύκλους.
- Δόθηκε το 16-8.
- APSK: 64-16
  όπως και το 1024-23 δείχνουν πως πυκώνουν αυτές οι διαμορφώσεις και μπορούν να
  προκαλέσουν τυχόν σφάλματα λόγω θορύβου.

- *Μεγαλύτερης τάξης αστερισμοί* χρησιμοποιούνται όταν:
  - SNR είναι ψηλό
  - (ισοδύναμα) το  κανάλι μας είναι καλό.
  Αυτό εδώ αναφέρθηκε ξανά και ξανά και στα επόμενα τμήματα της διάλεξης.


Κατόπιν ερώτησης αναφορικά με την κατάλληλη επιλογή διανυσμάτων/σημείων, ούτως
ώστε τα πιο /σημαντικά/ μας στοιχεία του μηνύματος να έχουν την μικρότερη
πιθανότητα επηρεασμού από τον θόρυβο, τονίστηκε πως δεν ενδιαφερόμαστε σε αυτή
την φάση για κωδικοποιημένη διαμόρφωση.

*** QAM
#+begin_note
Ουσιαστικά το επικρατέστερο πρότυπο ψηφιακής διαμόρφωσης σύμφωνα με όσα ειπώθηκαν.

#+end_note

Quadrature amplitude modulation (QAM)
- Χρησιμοποιούνται κατα κόρον (αναφέρθηκε πλήθος εφαρμογών. eg 5G)
- Υψηλότερης τάξης 1024 χρησιμοποιείται μεταξύ άλλων και στο Wifi 7 ()


*** HQAM
#+begin_note
Ουσιαστικά σχετική με την QAM αλλά έχουμε διαφορετική /σύνδεση/ των συμβόλων
μεταξύ τους.
#+end_note

Έχει πολύ καλύτερη αποδοτικότητα, από το τετράγωνο της SQAM, και λέγεται έτσι
διότι τα σημεία στο επίπεδο σχηματίζουν μεταξύ τους κανονικά εξάγωνα.

** Διαδικασία στον δέκτη                                           :noexport:
- Αυτό που θα παρουσιαστέι αύριο 
