#+title: Διαφορικές εξισώσεις πρώτης τάξης
#+description: Πιο συγκεκριμένα η επίλυση τους

Οι Διαφορικές εξισώσεις (από εδώ και στο εξής αναφερόμενες ως ΔΕ) χωρίζονται σε
κατηγορίες ανάλογα με τη μορφή και τις ιδιότητες τους. Συγκεκριμένα σημαντικό
ρόλο παίζουν η *τάξη* ( η μεγαλύτερη παράγωγος της ζητούμενης συνάρτησης που
εμφανίζεται και ο *βαθμός* ( δηλαδή η μεγαλύτερη δύναμη της μεγαλύτερης
παραγώγου).

* Γραμμικές

Ονομάζονται όλες οι εξισώσεις της μορφής:
\begin{equation}
\frac{d{y}}{d{x}} + p(x)y=q(x)
\end{equation}
και η γενική τους λύση είναι η:
\begin{equation}
y = e^{-\int p(x)dx}\int e^{\int p(x)dx}q(x)dx
\end{equation}
η οποία προκύπτει κατά τον πολλαπλασιασμό και των δύο μερών της αρχικής εξίσωσης
με τον όρο $e^{\int p(x)dx}$

** Σημαντική υποσημείωση
Στην επίλυση της εξίσωσης είναι σημαντικό να μην ξεχαστεί η σταθερά ολοκλήρωσης:
\begin{equation}
y = \cdots [ \int\cdots dx + c ]
\end{equation}

* Ricatti

Ονομάζουμε Δ.Ε. Ricatti κάθε ΔΕ πρώτης τάξης της μορφής:
\begin{equation}
\frac{d{y}}{d{x}}+f(x)y^2+g(x)y+h(x)=0
\end{equation}

** Επίλυση
Για την επίλυση μιας τέτοιας διαφορικής εξίσωσης χρειάζεται κανεις να ξέρει την
πρώτη εκ των δύο ριζών $y_1(x)$. Γνωρίζοντας την θέτεις $y = y_1 + \frac{1}{u}$
όπου $u$ καταλλήλως ορισμένη συνάρτηση.

* Bernoulli

Της μορφής:
\begin{equation}
\frac{d{y}}{d{x}} + g(x)y = f(x)y^n
\end{equation}

** Επίλυση
1. Διαίρεση με $y^n$
   Είναι προφανές πως θέλουμε να την φέρουμε σε μια μορφή πιο κοντά σε εκείνες
   που γνωρίζουμε, για αυτό και διαιρούμε με $y^n$ έτσι ώστε στο δεύτερο μέρος
   να μείνει μόνο η $f(x)$.
2. Θέσιμο $u = y^{1-n}$ και αναγωγή σε γραμμική ΔΕ
   Με αυτό τον τρόπο οι /παράξενοι όροι/ που περιλαμβάνουν αρνητικές δυνάμεις
   του $y$ /εξαφανίζονται/ και απομένει μόνο μια γραμμική ΔΕ πρώτης τάξης με
   άγνωστη συνάρτηση την $u(x)$
3. Επίλυση της γραμμικής και αντικατάσταση
   Λύνοντας την γραμμική με τον γνωστό τρόπο βρίσκουμε τον τύπο της $u(x)$ και
   αντικαθιστώντας $u = y^{1-n}$ έχουμε την πλεγμένη μορφή της λύσης(?)

* Ομογενείς ΔΕ

Αυτή η κατηγορία ΔΕ μπορεί να περιγραφεί από την

\begin{equation}
\frac{d{y}}{d{x}} = F(\frac{y}{x})
\end{equation}

/Κάτι πάει λάθος με τους διαφορετικούς ορισμούς σε πηγές/
** Επίλυση
1. Θέτουμε $y = ux$ όπου $u$ μια καταλλήλως ορισμένη συνάρτηση
2. Αντικαθιστούμε στην εξίσωση, μετατρέποντας την στην πιο απλή κατηγορία ΔΕ
3. Αντικαθιστούμε $u = \frac{y}{x}$

** Υποπεριπτώσεις
*** Επίλυση συστήματος
Αν δεν έχουμε την /αρχική/ μορφή ομογενούς ΔΕ αλλά:
\begin{equation}
\frac{d{y}}{d{x}}=f(\frac{a_1x+b_1y+c_1}{a_2x+b_2y+c_2})
\end{equation}
_και_ το σύστημα των δυο εξισώσεων:
\begin{align*}
\begin{cases}
a_1x+b_1y+c_1 &= 0\\
a_2x+b_2y+c_2 &= 0
\end{cases} \Rightarrow
\begin{cases}
x = x_0\\
y = y_{0}
\end{cases}
\end{align*}
τότε η ΔΕ λύνεται με αντικατάσταση $X=x-x_0$, $Y=y-y_0$, στο οποίο στάδιο εκείνη
ανάγεται σε ΔΕ χωριζόμενων μεταβλητών.

* ΔΕ χωριζόμενων μεταβλητών
Ονομάζονται οι ΔΕ πρώτης τάξης της μορφής:
\begin{equation}
\frac{d{y}}{d{x}} = p(x)q(y)
\end{equation}

Διότι, προφανώς εύκολα μετασχηματίζονται σε
\begin{equation}
\frac{dy}{q(y)}=p(x)dx
\end{equation}
όπου, ουσιαστικά, οι μεταβλητές είναι απομονωμένες στα διαφορετικά μέρη της
εξίσωσης και η λύση έρχεται με απλή ολοκλήρωση.

* Πλήρεις ΔΕ
Αποτελούν μια ιδιαίτερη /κατηγοριοποίηση/ ΔΕ πρώτης τάξης της μορφής:
\begin{equation}
P(x,y)dx + Q(x,y)dy = 0
\end{equation}

*ΑΝ* ισχύει: $\frac{\partial{P}}{\partial{y}}= \frac{\partial{Q}}{\partial{x}}$

Σε αυτή την περίπτωση η λύση δίνεται από την:
\begin{equation}
\int_a^x P(t,y)dt + \int Q(a,y)dy = c\in \mathbb{R}
\end{equation}

** Παρατήρηση
Στο ολοκλήρωμα η επιλογή της μεταβλητής $a$ πρέπει να είναι καταλλήλως ορισμένη
_και_ ιδανικά να βοηθάει με τις πράξεις ( συχνά καλή επιλογή αποτελεί το $0$ )

** Ολοκληρωτικός Παράγοντας
Υπο ορισμένες συνθήκες είναι δυνατός ο πολλαπλασιασμός της _μη πλήρους_
διαφορικής εξίσωσης με συνάρτηση $R$ καταλλήλως ορισμένη έτσι ώστε η τελική
εξίσωση:
\begin{equation}
P\cdot R(x,y)dx + Q\cdot R(x,y)dy = 0
\end{equation}
Να είναι πλήρης και να μπορεί να επιλυθεί με τον γνωστό τρόπο.


** Αναγωγή ΔΕ σε πλήρεις ΔΕ μέσω ολοκληρωτικού παράγοντα
Υπάρχουν ορισμένες περιπτώσεις στις οποίες ο ολοκληρωτικός παράγοντας προκύπτει
/τυποποιημένα/:
**** Απλή περίπτωση
Συνήθως, μάλιστα, είναι εύκολο αν είναι κανεις προσεκτικός να παρατηρήσει αυτή
την περίπτωση.
1. $\frac{1}{Q}(\frac{\partial{P}}{\partial{y}}-\frac{\partial{Q}}{\partial{x}})
   = F(x)$
   Σε αυτή την περίπτωση $R(x) = e^{\int F(x)dx}$
2. $\frac{1}{P}(\frac{\partial{Q}}{\partial{x}}-\frac{\partial{P}}{\partial{y}})
   = F(y)$
   όπου $R(y) = e^{\int F(y)dy}$
**** Σύνθετη
1. $\frac{1}{P-Q}(\frac{\partial{Q}}{\partial{x}}-\frac{\partial{P}}{\partial{y}})
   = F(x+y)$
   Τότε, για $z=(x+y)$ ο ολοκληρωτικός παράγοντας είναι:
    \[
    R(z) = e^{\int F(z)dz}
    \]
2. $\frac{1}{-(P+Q)}(\frac{\partial{Q}}{\partial{x}}-\frac{\partial{P}}{\partial{y}})
   = F(x-y)$
   Τότε, για $z=(x-y)$ ο ολοκληρωτικός παράγοντας είναι:
    \[
    R(z) = e^{\int F(z)dz}
    \]

*** Παρατηρήσεις

**** Προσοχή στο πρόσημο!
Είναι πολύ εύκολο να κάνει κανείς λάθος στο πρόσημο σε κάποιο από τα στάδια
αναγωγής διαφορικής σε πλήρη ΔΕ, και το αποτέλεσμα να μην έχει καμία σχέση με το
σωστό.
***** Κανόνας για τον /ελεγχο/ υποπεριπτώσεων:
Γενικά η συνάρτηση που βρίσκεται στον παρονομαστή πολλαπλασιαζόμενη με την
μερική παράγωγο της πρέπει να έχει αρνητικό πρόσημο ( δες περιπτώσεις ). Τώρα,
εξαίρεση αποτελεί η δεύτερη /σύνθετη/ περίπτωση, στην οποία μπορείς να σκέφτεσαι
ότι /προηγείται/ το αρνητικό πρόσημο του $Q$.
* Μη γραμμικές ως προς την παράγωγο

Μία ΔΕ η οποία μπορεί να μετασχηματιστεί στην μορφή[fn:1]:
\begin{equation}
(\frac{d{y}}{d{x}}-f_1(x,y))(\frac{d{y}}{d{x}}-f_2(x,y))=0
\end{equation}

Τότε, θεωρώντας πως
\begin{align}
y'=f_1\Rightarrow& g_1(x,y,c) = 0, c\in \mathbb{R}\\
y'=f_2\Rightarrow& g_2(x,y,c) = 0, c\in \mathbb{R}
\end{align}

Λύση της αρχικής εξίσωσης, σε πλεγμένη μορφή μπορεί να θεωρηθεί η:
\begin{equation}
g_1\cdot g_2=0
\end{equation}


* Footnotes
[fn:1] Μπορεί, με διαφορετικό βαθμό της ΔΕ να προκύψουν περισσότερες
/παραγοντοποιήσεις/ και /υποεξισώσεις/. Τα παραπάνω παραμένουν αληθή.
