#+title: whoami
#+properties: notoc

My name is Lamprinos Chatziioannou and I am a student at the school of
Electrical and Computer Engineering at A.U.Th. Always tinkering with new stuff, I
find myself spending most of the time feeling stuck in many fields and working
on others. Hopefully, I will find the time to see everything.

#+begin_quote
Mama told me when I was young\\
"Come sit beside me, my only son\\
And listen closely to what I say\\
And if you do this it'll help you some sunny day"\\

"Oh, take your time, don't live too fast\\
Troubles will come and they will pass\\
You'll find a woman and you'll find love\\
And don't forget, son, there is someone up above"\\

"And be a simple kind of man\\
Be something you love and understand\\
Baby, be a simple kind of man\\
Oh, won't you do this for me, son, if you can"\\


*Lynyrd Skynyrd*, Simple Man
#+end_quote

** The site itself
This site is nothing more than a collection of ~org-mode~ files, exported using
~org-publish~ inside of Emacs and hosted by Github Pages. 
