#+title: My first post
#+description: This is a test of a description

In my previous attempts to host my personal website the problem was obvious; I
focused too much on proper definitions about my blog that it took the whole fun
of writing out of it. I decided to avoid doing the same mistake again, which
translates into *more writing, less tinkering with the website*.

I will write on a plethora of subjects, books and ideas that I believe are worth
putting out so that they are improved.

Hopefully this is as good of an introduction as it can now get and will get
better, in time.

* References
I would really like to thank [[https://github.com/rougier][Nicolas P. Rougier]], for he is the creator of the
css theme that I have used in this website[fn:1]. I first saw it almost a year
ago from now when I first started reading on getting things done and I don't
think I have ever found a styling sheet that I like so much

I would also like to thank [[https://daviwil.com/][David Wilson]], for his excellent videos on Emacs,
letting me publish this website without too much hustle.

* Footnotes

[fn:1] The css file is available under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] at [[https://github.com/rougier/emacs-gtd/blob/master/GTD.css][rougier/emacs-gtd]]
