#+title: Starting again
#+date: [2022-02-17 Thu]
#+options: toc:nil

In my previous attempts to host my personal website the problem was obvious; I
focused too much on proper definitions about my blog that it took the whole fun
of writing out of it. I decided to avoid doing the same mistake again, which
translates into /more writing, less tinkering with the website/.

I will write on a plethora of subjects, books and ideas that I believe are worth
putting out so that they are improved.

Since I have not decided on a topic for an article yet, there are too many I'm
after and, to be frank, many that I'm afraid I won't do justice to, I have
decided to use the first _article_ in my website to thank two people I have
never met but to whom I attribute this /new try/ on a personal blog.

I would really like to thank [[https://github.com/rougier][Nicolas P. Rougier]],  for he is the creator of the
css theme that I have used in this website[fn:1]. I first saw it almost a year
ago when I first started reading on [[https://gettingthingsdone.com/][Getting Things Done]] and I don't
think I have ever found a styling sheet that I like so much

With that said, I feel it is not right not to mention his open-source work and
thank him for inspiring me (it still happens, every time I check his github
profile) to always try to do more.

Also, special thanks go to [[https://daviwil.com/][David Wilson]], for his excellent videos on Emacs,
helping me gain the most out of Emacs after being a vim user for more than 5
years. It was through his [[https://www.youtube.com/c/SystemCrafters][videos]], that I discovered how deep one could dive into
emacs and, more important to me, [[https://orgmode.org/][Org Mode]] configuration, allowing me to [[https://www.youtube.com/watch?v=AfkrzFodoNw][publish
my own website]], without /(relatively)/ much hassle.

* Footnotes

[fn:1] The css file is available under [[https://creativecommons.org/licenses/by/4.0/][CC BY 4.0]] at [[https://github.com/rougier/emacs-gtd/blob/master/GTD.css][rougier/emacs-gtd]]
