#+TITLE: Chasing simplicity
#+Description: Personal blog where I host my ece notes and ctf writeups. Powered by Emacs and Org Mode.
#+properties: notoc
#+INCLUDE: "./src/header.html" export html

I am an Electrical and Computer Engineering undergrad at [[https://ee.auth.gr/][A.U.Th]]. Always
tinkering with new stuff, you will most probably find me spending most of
the time feeling stuck in many fields and working on others. Such fields
/include yet are by no means limited to/: networks, security (in general),
programming, automation, mathematics and psychology. 

Hopefully, there will be time for everything.

** Ongoing projects
- I'm currently reading [[https://www.amazon.com/Outliers-Malcolm-Gladwell-audiobook/dp/B001LNK9C4/ref=sr_1_1?keywords=malcolm+gladwell+outliers+book&qid=1667322832&qu=eyJxc2MiOiIyLjA2IiwicXNhIjoiMS42MyIsInFzcCI6IjEuNzEifQ%3D%3D&sprefix=malcolm+gladwell%2Caps%2C212&sr=8-1][Malcolm Gladwell's Outliers]] and it has been quite a
  surprise. I had given /Talking to Strangers/ a shot but it did not quite capture
  my interest. This one, on the other hand... seems to have passed that test.
- Over the last couple days I have also tried my hand with [[https://github.com/rougier/matplotlib-tutorial][matplotlib]] and sympy.
  (/It is a very strange feeling seeing rougier in front of me so often/). Happy
  coincidence.
- My [[file:posts/lectures/auth/index.org][uni lecture notes]], are something I actively work towards improving,
  organizing and understanding. 

** Notes on the site itself.
- This site is nothing more than a collection of ~org-mode~ files, exported using
  ~org-publish~ inside of Emacs and hosted by Github Pages.
- Since I sometimes make quite elementary mistakes, [[https://youtube.com/watch?v=8Gv0H-vPoDc][I'm sorry for my word crimes]].
