#+TITLE: Chasing simplicity
#+SUBTITLE: Testing what's what
#+Description: Lamprinos' Chatziioannou personal blog where I host notes, book reviews and ctf writeups. Powered by Emacs and Org Mode.
#+properties: notoc
#+FILETAGS: index
#+INCLUDE: "src/header.html" export html

#+begin_center
I am an Electrical and Computer Engineering undergrad at [[https://ee.auth.gr/][A.U.Th]].
Always tinkering with new stuff, you will most probably find me
spending my time feeling stuck in many fields and working on others.

Actively working around networks and cybersecurity, while also dealing
with the stress being in that school may introduce into one's life.

Hopefully, there will be time for everything.
#+end_center

** Blog Hosted Tweets
Invert, always invert.

** [[file:posts/recents.org][Latest Articles]]
#+INCLUDE: "posts/recents.org" :lines "5-9" export html

** Notes on the site itself.
- This site, despite its minimalist approach, contains a plethora of hacks,
  inefficiently implemented ideas, Python, Bash, and Elisp scripts, along with
  various Org files and more :P. If you're not afraid of losing your sanity,
  feel free to explore the related GitHub repo.
- The code that reproduces the functionality is entirely open source. However,
  as stated more formally elsewhere, material published within my articles is
  licensed under [[https://creativecommons.org/licenses/by-nc-sa/4.0/][CC BY-NC-SA]], requiring attribution.
- Since I sometimes make rather elementary mistakes,
  [[https://youtube.com/watch?v=8Gv0H-vPoDc][I apologize for my word crimes]].
