#+INCLUDE: "./src/header.html" export html

I've always wanted to host a blog of my own, sharing what I think deserves to be
shared, documenting my progress and /tailoring/ it to my liking. It turns out
that I may have spent way too much time on the last part which, hopefully, one day I
will post about here. Till that day comes: [[https://youtube.com/watch?v=8Gv0H-vPoDc][I'm sorry for my word crimes]]

** [[file:posts/books/WylieCrawley_ThePentesterBlueprint.org][The Pentester Blueprint]]
<2022-03-30 Wed>\\
Some time ago I bought a /humble book bundle/ on Cybersecurity and it had
SOOOO MANY BOOKS. Seriously, when I learned that this bundle was available I
could not contain myself. Since then I have started reading some of these books,
always driven by the idea "/Read more books to read more/" and constantly
trying to improve my skills.


** [[file:posts/books/Mitnick2011-ghostinthewires.org][Ghost In The Wires]]
I started reading Mitnick's [[https://www.amazon.com/Ghost-Wires-Adventures-Worlds-Wanted-ebook/dp/B00FOQS8D6/ref=sr_1_1?keywords=ghost+in+the+wires&qid=1643737271&s=books&sprefix=ghost+in+the+wires%2Cstripbooks%2C198&sr=1-1][Ghost in the Wires: My Adventures as the Worlds Most
Wanted Hacker]], almost a month after finishing Menns's exceptional [[https://www.amazon.com/Cult-Dead-Cow-Original-Supergroup-ebook/dp/B07J5MW52M/ref=sr_1_1?crid=X6GLMYBDUOJO&keywords=cult+of+the+dead+cow&qid=1643840819&s=digital-text&sprefix=cult+of+the+dead+cow+%2Cdigital-text%2C173&sr=1-1][Cult of the
Dead Cow: How the Original Hacking Supergroup Might Just Save the World]]. Having
liked it so much and still intrigued in the history of the field, I chose to
dive in it a little bit more.

It surely did not disappoint me.

** [[file:posts/books/Menn2010_fatalsystemerror.org][Fatal System Error]]
Fatal System Error is a book targeted to a niche audience, that is for sure.

Menn's writing style has, from my experience, never been good. Personally, I do
not mind it, since I focus solely on the information given, yet it has never
been acceptable for literature, focusing more on the quantity of /facts and
details/ than the storyline. That is what makes this book, just like Menn's cDc,
such a difficult read. Writing this paragraph, it occured to me that the best
way to describe it would be: "/notes for an article-turned-book/". He has done a
tremendously good job gathering and evaluating information, but he did not
combine them properly. Had the author taken some extra time to polish the book,
maybe reading it more thorougly, I would have no trouble suggesting it to
*anyone*....
