#+TITLE: Chasing simplicity
#+Description: Lamprinos' Chatziioannou personal blog where I host notes, book reviews and ctf writeups. Powered by Emacs and Org Mode.
#+properties: notoc
#+INCLUDE: "./src/header.html" export html

I am an Electrical and Computer Engineering undergrad at [[https://ee.auth.gr/][A.U.Th]]. Always
tinkering with new stuff, you will most probably find me spending most of
the time feeling stuck in many fields and working on others. Such fields
/include yet are by no means limited to/: networks, security (in general),
programming, automation, mathematics and psychology. 

Hopefully, there will be time for everything.

** Ongoing projects
#+begin_comment
A now.org alternative.
#+end_comment

- The exam period is finally over and I am taking a moment to reorganize stuff,
  calm down and hopefully relax.
- Contrary to the previous bullet, I am taking the CCNA exam in the first half
  of the year and I spend quite a lot of time studying for it. 
- I published my very first emacs package: [[https://github.com/chatziiola/klp][KLP]], centered around notetaking and
  simplifying the creation and management of note files.
- In my spare time I'm trying to refactor my notetaking in lectures code, so
  that I publish that package as well, /open it up for feedback/ and ... take that
  section out of my configuration :P
  
** Latest Articles

** Notes on the site itself.
- This site is nothing more than a collection of ~org-mode~ files, exported using
  ~org-publish~ inside of Emacs and hosted by Github Pages.
- Since I sometimes make quite elementary mistakes, [[https://youtube.com/watch?v=8Gv0H-vPoDc][I'm sorry for my word crimes]].
