#+TITLE: Chasing simplicity
#+Description: Lamprinos' Chatziioannou personal blog where I host notes, book reviews and ctf writeups. Powered by Emacs and Org Mode.
#+properties: notoc
#+INCLUDE: "./src/header.html" export html

I am an Electrical and Computer Engineering undergrad at [[https://ee.auth.gr/][A.U.Th]]. Always
tinkering with new stuff, you will most probably find me spending most of
the time feeling stuck in many fields and working on others. Such fields
/include yet are by no means limited to/: networks, security (in general),
programming, automation, mathematics and psychology. 

Hopefully, there will be time for everything.

** Ongoing projects
#+begin_comment
A now.org alternative.
#+end_comment

- Studying, like a lot. This exam period is gonna be more difficult than I
  expected at the beginning of the year.
- Got back to an adequate rhythm of reading books (outside of school), so that's
  a something
- Tinkered around with a next/previous button in my lectures as you can see in
  [[file:posts/20221228_elisp-org-publish-blog-configuration.org][my publish-blog post]], however it is not working as intended. I'll have to fix
  it sooner or later.
  
** Latest Articles

** Notes on the site itself.
- This site is nothing more than a collection of ~org-mode~ files, exported using
  ~org-publish~ inside of Emacs and hosted by Github Pages.
- Since I sometimes make quite elementary mistakes, [[https://youtube.com/watch?v=8Gv0H-vPoDc][I'm sorry for my word crimes]].
