#+TITLE: Chasing simplicity
#+Description: Lamprinos' Chatziioannou personal blog where I host notes, book reviews and ctf writeups. Powered by Emacs and Org Mode.
#+properties: notoc
#+INCLUDE: "./src/header.html" export html

I am an Electrical and Computer Engineering undergrad at [[https://ee.auth.gr/][A.U.Th]]. Always
tinkering with new stuff, you will most probably find me spending most of
the time feeling stuck in many fields and working on others. Such fields
/include yet are by no means limited to/: networks, security (in general),
programming, automation, mathematics and psychology. 

Hopefully, there will be time for everything.

** Ongoing projects / A ~now.org~ alternative
On a roll, tackling the exam period head-on, which translates into
ridiculously low free time and peace of mind, knowing that things are
going to get worse before they get better. It is what it is I suppose
and having lots of stuff to do (letting deadlines aside for a moment
:P) never bothered me.

Some songs for those few cold days (and nights), when some
adrenaline coupled with one's discipline and determination may allow
for optimal performance:
- [[https://www.youtube.com/watch?v=WmP4iTGY97Y][Helloween: Power]]
- [[https://www.youtube.com/watch?v=NLP0xP2M4S8][Pantera: Becoming]] 
- [[https://www.youtube.com/watch?v=360xvnsduDg][and a metal god classic]]


  
** Latest Articles

** Notes on the site itself.
- This site is nothing more than a collection of ~org-mode~ files, exported using
  ~org-publish~ inside of Emacs and hosted by Github Pages.
- Since I sometimes make quite elementary mistakes, [[https://youtube.com/watch?v=8Gv0H-vPoDc][I'm sorry for my word crimes]].
