#+TITLE: Chasing simplicity
#+Description: Lamprinos' Chatziioannou personal blog where I host notes, book reviews and ctf writeups. Powered by Emacs and Org Mode.
#+properties: notoc
#+INCLUDE: "./src/header.html" export html

I am an Electrical and Computer Engineering undergrad at [[https://ee.auth.gr/][A.U.Th]]. Always
tinkering with new stuff, you will most probably find me spending most of
the time feeling stuck in many fields and working on others. Such fields
/include yet are by no means limited to/: networks, security (in general),
programming, automation, mathematics and psychology. 

Hopefully, there will be time for everything.

** Ongoing projects
#+begin_comment
A now.org alternative.
#+end_comment
- Last week I finished [[Malcolm-Gladwell-audiobook/dp/B001LNK9C4/ref=sr_1_1?keywords=malcolm+gladwell+outliers+book&qid=1667322832&qu=eyJxc2MiOiIyLjA2IiwicXNhIjoiMS42MyIsInFzcCI6IjEuNzEifQ%3D%3D&sprefix=malcolm+gladwell%2Caps%2C212&sr=8-1][Malcolm Gladwell's Outliers]]. I found it really
  interesting and I'm thinking of /maybe/ modifying my approach to the blog a
  little bit to add a concise summary and review of it. 
- I decided to give learning Chinese a try and, I have to say, [[https://www.archchinese.com/chinese_handwriting_practice.html][sketching Chinese
  characters]] is interestingly soothing.
- I've been preparing for the HTB: University CTF competition
- Finally, because the exam period looms ahead, studying and getting up to date
  with my university courses takes an even bigger percentage of my time
 

** Notes on the site itself.
- This site is nothing more than a collection of ~org-mode~ files, exported using
  ~org-publish~ inside of Emacs and hosted by Github Pages.
- Since I sometimes make quite elementary mistakes, [[https://youtube.com/watch?v=8Gv0H-vPoDc][I'm sorry for my word crimes]].
