#+TITLE: Chasing simplicity
#+Description: Lamprinos' Chatziioannou personal blog where I host notes, book reviews and ctf writeups. Powered by Emacs and Org Mode.
#+properties: notoc
#+INCLUDE: "./src/header.html" export html

I am an Electrical and Computer Engineering undergrad at [[https://ee.auth.gr/][A.U.Th]].
Always tinkering with new stuff, you will most probably find me
spending my time feeling stuck in many fields and working on others.

Actively working around networks and cybersecurity, while also dealing
with the stress being in that school may introduce into one's life.

Hopefully, there will be time for everything.

** Ongoing projects / A [[https://sive.rs/nowff][now]] [[https://nownownow.com/about][alternative]]
Took some time to myself this weekend and channeled my (not-so)
inner-child into fixing some aspects of this blog that increased the
tension between me and writing more. This was (at least from my point
of view) a giant success, greatly simplifying some obscure parts of my
configuration and allowing for a more unified process in the export
stages.

P.S. I was ready to publish the blog (for the final time today) and go
back for a final study session, but I felt it was my duty to express
my thesis on the latest happenings in Greek Universities. While
initially myopic, thinking only of the potential benefits the
introduction of private (non-governmental) universities could have had
in the Greek society and hoping for it to (partly) mitigate the
brain-drain phenomenon, the dangers it introduces along with the
strange circumstances around this legislative phenomenon, has me in
doubt. I just wish it was more openly discussed, allowing for more
voices and opinions to be heard.

I intend to post an article about it sometime in the future, should my
progress in preparing for the exams be sufficient. Too much
polarization even among those who /fight/ for the same stuff.
  
** Latest Articles
# recents start

- 2024-01-21: [[../posts/20240121_hackerone_ctf_challenges.org][HackerOne: CTF: Micro-CMS]]
- 2023-12-27: [[../posts/20231227_making_my_life_easier.org][Make-ing my life easier]]
- 2023-12-27: [[../posts/20231227_thm_game_zone.org][THM: Game Zone]]
- 2023-12-15: [[../posts/20231215_sigh_hasta_la_vista_thm_skynet.org][Sigh...Hasta La Vista: THM: Skynet]]
- 2023-12-14: [[../posts/20231214_back_again_thm_hackpark.org][Back Again: THM Hackpark]]
# recents end

** Notes on the site itself.
- +This site is nothing more than a collection of ~org-mode~ files, exported using ~org-publish~ inside of Emacs and hosted by Github Pages.+
  This site, although aesthetically minimal, consists of a plethora of hacks,
  inefficiently implemented ideas, python, bash and elisp scripts, org
  files and some more :P. If you are not afraid of losing your sanity,
  feel free to wonder in the related github repo.
- The code to reproduce the functionality is all open source, however,
  as pointed more formally elsewhere, material published within my
  articles should be considered [[https://creativecommons.org/licenses/by-nc-sa/4.0/][CC BY-NC-SA]] licensed, requiring
  attribution. 
- Since I sometimes make quite elementary mistakes,
  [[https://youtube.com/watch?v=8Gv0H-vPoDc][I'm sorry for my word crimes]].
