#+title: Books
#+HTML_LINK_UP: ../index.html
#+OPTIONS: toc:no

# Lines starting with # are comments: do not change them

#  Introduction
When I first started creating my personal website, it was due to a
peculiar combination of a need to express and put myself out there,
and a heartwarming nostalgic feeling, of the time I used to write for
my school's newspaper.

# 
Having been called a bookworm for the best part of my life, I take
immense pride in reading. And it is not just literature books, but
whatever I can get my hands on. I may have gotten a little picky in
these last years but the list of books I want/plan to read has kept
increasing (exponentially).

#
This is where this index page comes into play! Here, from time to
time, I will share some book reviews or posts about ideas discovered
within them!

* Book Reviews
I am not entirely satisfied with the quality of the articles here: I
know they could have been written much more carefully, and
structured in a much more coherent manner than they currently are.
Maybe it is a good idea to update them in the future, but so far I
have, instead, settled on this: "They should be kept here, since these
were some of my first articles on this blog"

- [[file:Mitnick2011-ghostinthewires.org][Mitnick,Simmons2011 - Ghost In The Wires]]
- [[file:Menn2010_fatalsystemerror.org][Menn2010 - Fatal System Error]]
- [[file:WylieCrawley_ThePentesterBlueprint.org][WylieCrawley2020 - The Pentester Blueprint]]


