#+TITLE: Διάλεξη (1)  : Υλική εξέλιξη των δικτύων.
#+FILETAGS: lecture
#+DATE: <2023-03-14>
#+FILETAGS: lecture
#+COURSE: CN1
#+INSTITUTION: A.U.Th

* Εισαγωγή (επανάληψη στα της αρχικής διάλεξης)

Με το κόστος του δικτύου, ζητούμενη ισορροπία με QoS:
  
\begin{equation}
\label{eq:1}
M = N^2 \Rightarrow M=N \Rightarrow M<<N
\end{equation}
όπου στην παραπάνω εξίσωση:
- Μ το πλήθος των γραμμών
- Ν το πλήθος των hosts

Το τρίτο μέρος της eqref:eq:1, έχει το εξής προβληματικό χαρακτηριστικό: κατα
την περαιτέρω μείωση των γραμμών το QoS (Quality Of Service) πέφτει δραματικά.

Γενική αναφορά σε LANs, WANs, και την μεταξύ των σύνδεση.

* Circuit Switching (Μεταγωγή κυκλώματος)
  #+begin_comment
- Το αναφέρει ως ξεχωριστό του packet switching
wtf signaling (εμμόνή με HW)
  #+end_comment

- Κλήση με dialing, (από όσο κατλαβαίνω πρόκειται για χρήση επί τηλεφωνικών γραμμών)
  - Receiver, Transceiver

- Γενική αναφορά στην (από πίσω) υποδομή, αναφερόμενος στους κατανεμητές και τον
  κεντριό κατανεμητή, καταλήγοντας εκεί από το σπίτι μας σε μορή συνεχούς
  ηλεκτρικής σύνδεσης.

  #+begin_comment
κατα μητράκο η εξέταση τέτοιων συστημάτων επεξηγεί τις επιδόσεις στα σύγχρονα συστήματα
  #+end_comment



- Αναλογικές επικοινωνίες και τρόπος λειτουργίας
  - TODO φτιάξε απλό κύκλωμα με τηλέφωνο και ...
  - προσπάθησε να επεξηγήσεις (κάνοντας και γράφημα εξόδου) το πως από την
    μεμβράνει που συμπιέζει αποσυμπιέζει τα ψήγματα άνθρακα, το ρεύμα εξόδου. ..
  - Μπαταρίες για την διαμόρφωση του κυκλώματος

- Λειτουργία του /περιστροφικού επιλογέα αριθμών (καντραν)/ ?, σταθερή κυκλική
  συχνότητα κατά την επιστροφή, παράγοντας παλμούς DC (επιτελεί την λειτουργία
  signaling)
  - αριθμός +2 παλμούς ανα αριθμό
  - αν χανόταν παλμός, λόγω του τύπου λειτουργίας θα πέρναμε λάθος νούμερο.

- Simplex λειτουργία (???)
- ότι μόνο ο ένας μπορεί να μιλήσει και ο άλλος μόνο να ακούσει
- πρόγονος της half, full duplex

- Full duplex equivalent, μικρόφωνο και μεγάφωνο μέσω μετασχηματιστών επί
 κοινού μέσου (κάνε τετράγωνο με τέσσερα πηνία) - έχω όμως echo, όπως φαίνεται
 στο σύστημα, άλλωστε δεν υπάρχει διαχωρισμός μεταξύ των ακουστικός
  - echo cancelling (παλαιότερα σε hardware), πλέον ολοκληρωτικά digitally
    - Παλιό canceling με αφαιρέτη (συνδεόμενο με το μικρόφωνο)
    - απαραίτητο και για γραμμές δεδομένων (συστημάτων)
    - Είναι διαταξη της μορφής ADSL (A for Asymetric TODO (fix this))
  - Η αλλαγή της διάταξης είναι ο λόγος για τον οποίο (ξεχωριστή πηγή ενέργειας
    για το τηλέφωνο - αντί για μπαταρίες) πλέον τα τηλέφωνα δεν λειτουργούν κατα
    την διάρκεια διακοπής ρεύματος.


- Εξέλιξη: number matrix αντί για περιστροφικού δίσκου (αυτό λέγεται και πινακας
  αριθμών). Είναι αδιάφορο το κυκλωματικό μέρος - προκαλούν την λειτουργία
  τοπικών ταλαντωτών... περιορισμός στα 4kHz. Συχνότητες εντός του τηλεφωνικού
  φάσματος μεταφέρονται με το πάτημα κουμπιού, και αναγνωρίζονται στο σημείο
  εισόδου του παρόχου (filter bank), αναγνωρίζοντας τον αριθμό.
  - Σύνολο BPF Filters (σχεδιάστηκαν με τρεις ~, εκ των οποίων οι δύο
    διεγραμμένες).
    Με αυτό το σύστημα αναγνωρίζεται η έξοδος απο δύο φίλτρα, δείχνοντας το
    ατάλληλο νούμερο. Η τεχνολογία ονομάζεται DTMF
  - Ενδιαφέρουσα εφαρμογή αυτού συναντάται στα αυτοματοποιημένα τηλεφωνικά
    κέντρα "πατήστε 1" ...

    #+begin_note
Για μεταβατική περίοδο, τηλέφωνα που εξυπηρετούν και τις δύο ουσιαστικά
τεχνολογίες (διακοπτάκι TP απο κάτω (TONE, PUNCH))
    #+end_note

- Παλαιά διαρρύθμιση του ΟΤΕ κατ' αυτόν τον τρόπο:
  - Κολώνες σαν αυτές της ΔΕΗ, ...

- Αντικατάσταση με FDM συστήματα:
  - LPF @4KHz
    #+begin_note
Προβληματική για το διαδίκτυο σύμβαση που ίσχυσε στα δίκτυα φωνής
    #+end_note
  - Πολλαπλασιασμός με διάφορα (ξεχωριστά φέροντα)
  - άθροισμα των επιμέρους /διαμορφωμένων-μετατοπισμένων/ σημάτων, και περαιτέρω
    μετατόπιση με φίλτρο RF, ούτως ώστε αυτή εν συνεχεία να μπορεί να υπάρξει
    εκπομπή
  - Line Of Sight .. κτλ κτλ:
    - Γράψε ακόμα για το πλήθος καναλιών (ξέρω εγώ 1000 κανάλια των 4Khz) τα
      οποία, λόγω αθροίσματος πρίν τον RF, έχουν ένα συνολικό μέγεθος (επι του
      παραδείγματος) 4Mhz, επιτρέποντας την πολύ εύκολη /μετατόπιση-διαμόρφωση/
      από τον RF ενισχυτή-φίλτρο.

      #+begin_note
Γράψε περί της βελτιώσης που αυτό προσφέρει
      #+end_note

- Και αυτή η τεχνολογία ξεπεράστηκε:
  - Αντί να συνδέεται πλέον σε πιάτο (κεραία) για να σταλεί ασύρματα
  - coaxial cable
  - 2 σύρματη γραμμη,
  - Άνετα περνάει 1GHz σε 100 χιλιόμετρα.

TODO βάλε εδώ εικόνα coaxial cable, το έδειξε και ήταν πού απλή ανάλυση.


Μετάβαση από FDM σε TDM:
- Προστέθηκε: DFDM, DTDM, ενώ τονίστηκε πως εμείς θα μπλέξουμε με SFDM STDM
  - Deterministic
  - Statistical

    TODO βάλε σχεδιάγραμμα, τρεις εισερχόμενες γραμμές με A/D στην είσοδο και
    ενισχυτές που καταλήγουν επί ομοαξονικού καλωδίου.

- Analog to Digital in voice:
  - 4KHz
  - Nyquist: 2x4ksamples/sec:
  - 8bits/samples (κβάντιση.)
  - Συνδυάζονας όλα τα παραπάνω 64Kbps (πρέπει να είναι bit)
    - PCM voice channel

- Κανάλια επί ομοαξονικού καλωδίου, ανάγκη TDM σε αυτή την περίπτωση, έγινε απλή
  σχηματική αναπαράσταση.
  - Κάτι πήγε εκεί με τους ενισχυτές και την συμπεριφορά σε TDM???
  - Δεν είναι απλά ενισχυτές αλλά έχουν θεωρητικά κάποιο χρονοκύκλωμα να συνδέει
    την λειτουργία τους.

- Διαμόρφωση του σήματος σε υποδιαιρέσεις του παλμού PCM
  - Έτσι το έδειξε σε εικόνα ο μητράκος.

- 64... 1000MBps 
  - Θεωρώ απλά κατα λάθος το έγραφε.

- Και φτάσαμε μέχρι την οπτική ίνα
  - Grading - κυματοδήγηση κτλ κτλ

