#+TITLE: Διάλεξη 5(1): Θεωρήματα Lyapunov
#+FILETAGS: lecture
#+DATE: <2023-03-17>
#+FILETAGS: lecture
#+COURSE: SAE2
#+INSTITUTION: A.U.Th


#+begin_note
Το συγκεκριμένο μάθημα απο εδώ και στο εξής θα ακολουθήσει την αρίθμηση 1,2,3
(κλασσική), όμως το 5 εδώ δείχνει πως ουσιαστικά /πρέπει/ να έγιναν 4 διαλέξεις
στις οποίες δεν μπόρεσα να παω τις πρώτες βδομάδες
#+end_note

* Εισαγωγή
Περιορισμός του αντικειμένου του μαθήματος σε γραμμικά συστήματα, δηλαδή σε
συστήματα που περιγράφονται από εξισώσεις της μορφής:

\begin{equation}
\label{eq:1}
{\dot x} = F(x) \Rightarrow {\dot x} = Ax
\end{equation}

όπου $x$ το διάνυσμα καταστάσεων, και $A$ matrix, όπου:
- $A$ τετραγωνικός πίνακας, όπου αν $det(A)=0$, από ΓΑ: $Ax=0\Rightarrow x=0$
- $x^{*}$: Σημείο ισορροπίας του συστήματος.

Η ευστάθεια υπολογίζεται από τις ιδιοτιμές του πίνακα $A$:
- Αρνητικό πραγματικό μέρος σε *όλες* τις ιδιοτιμές ενός συστήματος -> ασυμπτωτικά ευσταθές
- Αν έστω και μία ιδιοτιμή έχει θετικό πραγματικό μέρος -> ασταθές.

- Η ευστάθεια είναι χαρακτηριστικό του συστήματος.
  - Μόνο για γραμμικά
  - Μιλάμε για ευστάθεια συστήματος και όχι σημείου ισορροπίας

* Ειδικές περιπτώσεις πίνακα $A$
- Αν ο $A$ διαγώνιος ή τριγωνικός, ως γνωστόν τα στοιχεία της διαγωνίου είναι οι
  ιδιοτιμές:
  - Σε αυτή την περίπτωση προφανώς καθώς:[fn:1]
\begin{equation}
\label{eq:3}
{\dot x}_j = \lambda_jx_j \Rightarrow \cdots \Rightarrow x_j(t) = x_j(0)e^{\lambda_jt}
\end{equation}

- Μηδενική ορίζουσα
- Τετραωνικός (μπλόκ - δεν θυμάμαι ονοματολογία) πίνακας
  
\begin{equation}
\label{eq:4}
\begin{bmatrix}
\begin{bmatrix}
\sigma_1 & \omega_1\\
\sigma_2 & \omega_2\\
\end{bmatrix} & \cdots & 0\\
\vdots & \ddots & \vdots\\
0 & \cdots &
\begin{bmatrix}
\sigma_n & \omega_n\\
\sigma_n & \omega_n\\
\end{bmatrix} 
\end{bmatrix}
\end{equation}

Κάπως έτσι όμως ισχύουν διαφορετικές σχέσεις μεταξύ των στοιχείων των εσωτερικών
πινάκων ούτως ώστε
\begin{equation}
\label{eq:5}
\begin{bmatrix}
\sigma_1 & \omega_1\\
-\omega_1 & \sigma_1
\end{bmatrix}
\end{equation}


Οπότε σε εκείνες τις περιπτώσεις οι λύσεις μας είναι *προφανώς* πιο σύνθετες.
Αρχικά έχουμε μιγαδικές ιδιοτιμές της μορφής:
\begin{equation}
\label{eq:6}
\lambda_j = \sigma_j \pm \jmath \omega_j
\end{equation}

Ενώ οι ίδιες οι ρίζες του συστήματος:
\begin{equation}
\label{eq:7}
x_{2j-1}(t) = e^{\sigma_jt}(x_{2j-1}(0)\cos{\left(\omega_jt\right)}+x_{2j}(0)\sin{\left(\omega_jt\right)})
\end{equation}

εδώ φαίνεται ότι έχουμε ταλάντωση, και πάλι ο εκθετικός όρος είναι ενδεικτικός
της κρισιμότητς του αρνητικού πραγματικού μέρους ως *αναγκαστικό* στοιχείο για την
ευστάθεια του συστήματος.

* Παράδειγμα: Εξέταση ευστάθειας                                 :example:

Έχουμε σύστημα της μορφής:
\begin{equation}
\label{eq:8}
{\dot x} = 
\begin{bmatrix}
-k_0 -k_1 & k_1\\
k_2 & -k_2
\end{bmatrix}x + 
\begin{bmatrix}
b_0\\0
\end{bmatrix}u
\end{equation}

Θέλουμε να σχεδιάσουμε ελεγκτή ο οποίος να εξαρτάται μόνο από την έξοδο και να
εξασφαλίζει ότι εκείνη θα οδηγείται στο 0.

Θέλουμε να χρησιμοποιήσουμε ένα γενικό ελεγκτή της μορφής:
\begin{equation}
\label{eq:9}
u = -kx_2
\end{equation}

#+begin_note
Γραμμική ανάδραση /μεταβολής/ 
#+end_note

Αντικαθιστώντας στην eqref:eq:8, έχουμε:
\begin{equation}
\label{eq:10}
{\dot x} = 
\begin{bmatrix}
-k_0 -k_1 & k_1\\
k_2 & -k_2
\end{bmatrix}x + 
\begin{bmatrix}
-b_0kx_{2}\\0
\end{bmatrix}
\end{equation}


Και όμορφα, συνδυάζοντας τα σε έναν μόνο πίνακα:
\begin{equation}
\label{eq:11}
{\dot x} = 
\begin{bmatrix}
-k_0 -k_1 & k_1-kb_0\\
k_2 & -k_2
\end{bmatrix}x \Rightarrow
{\dot x} = Ax
\end{equation}


Καθώς όλα τα στοιχεία μεγαλύτερα του 0 ($k_i >0$):
\begin{equation}
\label{eq:12}
det(A) = \cdots > 0
\end{equation}

Που σημαίνει ότι ο πίνακας $A$ έχει βαθμό 2, οπότε και συνεχίζουμε υπολογίζοντας
τις ιδιοτιμές:
\begin{equation}
\label{eq:13}
det(sI - A) = 0 \Rightarrow \cdots \Rightarrow  s^2+ (k_0+k_1+k_2)s + k_2(b_0k+k_0) = 0
\end{equation}

Η ευστάθεια σε αυτό το σημείο μπορεί να εκτιμηθεί με 2 τρόπους:
- Τρόπος 1: Κλασσικός με διακρίνουσα.
  Λύνεις την εξίσωση και βγάζεις τις ιδιοτιμές συναρτήσει των $k_{i}, b_0$. Σε
  αυτή την φάση, απλά ενδιαφερόμαστε για να έχουν αρνητικό πραγματικό μέρος,
  οπότε περιορίζεις τις επιλογές αντίστοιχα
- Τρόπος 2: Κριτήριο Routh.
  Αντί να παιδεύεσαι να λύνεις εξισώσεις, που μπορεί (αρκετά συχνά) να είναι πιο
  δύσκολες από αυτές που εξετάζονται σε αυτό το παράδειγμα, εφαρμόζεις το
  κριτήριο Routh, όπως αυτό έχει /καλυφθεί/ στα ΣΑΕ1 (δεν υπάρχει στο υλικό που
  είναι ανεβασμένο, υπάρχει όμως λινκ για τις σημειώσειες Κανναβούρα).
  - Αρκεί (μόνο για 2ο βάθμια συστήματα): να είναι όλοι οι όροι ομόσημοι του
    μεγιστοβάθμιου.

    
* Επιστροφή στα μη γραμμικά συστήματα
Στα μη γραμμικά συστήματα η ανάλυση ευστάθειας γίνεται με δύο κυρίως τρόπους:
#+begin_note
Και οι δύο τεχνικές δημοσιεύτηκαν από τον [[https://en.wikipedia.org/wiki/Aleksandr_Lyapunov][Lyapunov]].
#+end_note

** Έμμεση μέθοδος ευστάθειας
#+begin_note Έλεγχος σε περιοχή
Επί του θεωρήματος. Με το εξεταζόμενο θεώρημα (πρώτο θεώρημα του Lyapunov)
ελέγχουμε μόνο κοντά σε εκείνη την περιοχή
#+end_note
Ισοδύναμα, το πρώτο θεώρημα του Lyapunov.

Δοθέντος συστήματος που περιγράφεται από την:
\begin{equation}
\label{eq:14}
{\dot x} = F(x)
\end{equation}

Αν ένα σημείο ισορροπίας είναι το $x^{*}$:
\begin{equation}
\label{eq:15}
{\dot x} = F(x^{*}) + \frac{\partial{F}}{\partial{x}}(x-x^{*})+ R(|x-x^{*}|)
\end{equation}

Αν το $x^{*}$, επαρκώς κοντά στο $x$, τότε οι τελευταίοι πίνακες εξαφανίζονται
καθώς αποκτούν απειροελάχιστη τιμή τελικά έχουμε:

\begin{equation}
\label{eq:16}
{\dot x} = A (x-x^{*}) \Rightarrow {\dot x} = Az
\end{equation}

Αλλάζω μεταβλητή ώστε να είναι στην μορφή που έχουμε συνηθίσει να μελετάμε τα
συστήματα. Για την καινούρια μεταβλητή ισχύει:

\begin{equation}
\label{eq:17}
z^{\cdot} = {\dot x}
\end{equation}

*** Φυσικό παράδειγμα εκκρεμούς                                   :example:

\begin{equation}
\label{eq:19}
{\dot x} = 
\begin{bmatrix}
x_2 \\ \sin{\left(x_1\right)} - \gamma x_2
\end{bmatrix}
, \gamma>0
\end{equation}

Τα σημεία ισορροπίας έχουν βρεθεί σε προηγούμενη άσκηση:
\begin{equation}
\label{eq:20}
(0,0), (\pi,0)
\end{equation}

(Μπορούν εύκολα να βγουν βέβαια και από την λογική μας αντίληψη. Το εκκρεμές
έχει ένα σημείο ισορροπίας στην κορυφή, το οποίο όμως είναι ασταθές, και ένα που
είναι ευσταθές στο κατώτερο σημείο της τροχιάς του.)

Πρέπει να βγάλουμε ξεχωριστή μελέτη για κάθε σημείο ισορροπίας. Προκειμένου να
είναι ευσταθές το σύστημα, θα πρέπει να είναι ευσταθές σε κάθε σημείο
ισορροπίας(?).

**** Εξετάζοντας το πρώτο σημείο
- Για μικρές γωνίες: $\sin{\left(x_1\right)}\approx x_1$, οπότε και να κάνω την
  αντικατάσταση επί του πίνακα:
  
\begin{equation}
\label{eq:21}
{\dot x} = 
\begin{bmatrix}
x_2 \\ x_1 - \gamma x_2
\end{bmatrix}
\end{equation}

Το οποίο φέρνοντας το στην κατάλληλη μορφή ${\dot x} = A x$:

\begin{equation}
\label{eq:22}
{\dot x} = 
\begin{bmatrix}
0 & 1\\ 1 & -\gamma
\end{bmatrix}
x
\end{equation}

Είναι προφανές ότι :
\begin{equation}
\label{eq:23}
\det(sI - A) = 0 \Rightarrow s^2 + \gamma s -1 = 0
\end{equation}

Από [[*Παράδειγμα: Εξέταση ευστάθειας][το σχόλιο για την εφαρμογή του Routh σε δευτεροβάθμια εξίσωση]] το σύστημα δεν
είναι ευσταθές σε αυτό το σημείο ισορροπίας.

**** Εξετάζοντας το δεύτερο σημείο
#+begin_note Αλλαγή μεταβλητής
Αν το σημείο ισορροπίας είναι το 0, καλώς. Αν όχι χρειάζεται να κάνουμε αλλαγή
μεταβλητής της μεταβλητής: $z = x- x^{*}$. Αυτό είναι επιτρεπτό χωρίς βλάβη της γενικότητας.
#+end_note
Για το δεύτερο σημείο, προκειμένου να κάνω την ίδια ανάλυση, *χρειάζεται να θέσω
μεταβλητή* ώστε το εξεταζόμενο σημείο ισορροπίας (στην καινούρια μεταβλητή) να
είναι το 0.
  
\begin{equation}
\label{eq:24}
z = 
\begin{bmatrix}
z_1\\z_2
\end{bmatrix} = 
\begin{cases}
z_1 &=  x_1 - \pi\\
z_2 &= x_2\\
\end{cases}
\end{equation}

Οπότε, όπως δείχνει η eqref:eq:22
\begin{equation}
\label{eq:2}
{\dot z} = \begin{bmatrix}
z_2 & 0 \\ \sin{\left(z_1+\pi\right) &-\gamma z_2}
\end{bmatrix}
\end{equation}

(Θέλουμε πάλι να κάνουμε προσέγγιση):
\begin{equation}
\label{eq:26}
\sin{\left(z_1+\pi\right)} = - \sin{\left(z_1\right)} \stackrel{\text{around } 0}{\approx} - z_{1}
\end{equation}

Έτσι:
\begin{equation}
\label{eq:25}
{\dot z} = 
\begin{bmatrix}
0 & 1\\ -1 & -\gamma
\end{bmatrix}z
\end{equation}

Και, με την ίδια διαδικασία καταλήγουμε:

\begin{equation}
\label{eq:27}
\det(sI - A) = 0 \Rightarrow s^2 +\gamma s +1 = 0
\end{equation}

οπότε το συγκεκριμένο σημείο ισορροπίας είναι ευσταθές.

Το σύστημα, όμως, γενικά δεν είναι ευσταθές (?) - Δεν θα έπρεπε να είναι?.


** Αναγκαίος ορισμός: Θετικά/Αρνητικά ορισμένη συνάρτηση
#+begin_comment
Η ιδέα: αποδεικνύοντας γνησίως φθίνουσα μορφή του συστήματος ...
#+end_comment


Οριζουμε συνάρτηση: $V: {\mathbb R}^n \to {\mathbb R}$. Εκείνη ονομάζεται θετικά
ορισμένη αν και μόνο αν:
\begin{equation}
\label{eq:29}
V(x) > 0 \forall x\neq 0
\end{equation}
ΚΑΙ
\begin{equation}
\label{eq:30}
V(0) = 0
\end{equation}

Αντίστοιχα, αρνητικά ορισμένη αν αντιστρέφεται η πρώτη σχέση eqref:eq:29:
\begin{equation}
\label{eq:18}
V(x)<0 \forall x \neq 0
\end{equation}


*** Προσοχή στον ορισμό                                           :example:
Έστω ότι έχουμε αυτές τις δύο συναρτήσεις, και θέλουμε
\begin{align*}
\label{eq:31}
V_1(x_1,x_2) &= x_1^2 + x_2^2\\
V_2(x_1,x_2) &= x_1^{2}
\end{align*}
Απο αυτές τις δύο ποιά είναι θετικά ορισμένη?

Μόνο η $V_1$.
Η $V_2$ είναι θετικά *ήμι* ορισμένη...

** Άμεση μέθοδος ευστάθειας
Δεύτερο θεώρημα του Lyapunov.

#+begin_note
Δυστυχώς δεν κράτησα καλές σημειώσεις απο ότι φαίνεται στο συγκεκριμένο κομμάτι.
Με την πρώτη ευκαιρία, κατόπιν μελέτης θα ενημερώσω αυτό το section, πιθανότατα
με βιβλιογραφικές παραπομπές.
#+end_note

Έστω /κλασσικά/ σύστημα της μορφής:
\begin{equation}
\label{eq:28}
{\dot x} = F(x)
\end{equation}
και σημείο ισορροπίας $x^{*}$

Έστω θετικά ορισμένη συνάρτηση: 
\begin{equation}
\label{eq:33}
V(x) >0
\end{equation}

Αν δείξουμε ότι:
\begin{equation}
\label{eq:32}
{\dot V} = \frac{\partial{V}}{\partial{x}}^T {\dot x} = \frac{\partial{V}}{\partial{x}}^T F(x) \leq 0
\end{equation}

\begin{equation}
\label{eq:34}
B_r(0) = \left\{ x\in {\mathbb R}^n : |x| < r\right\}
\end{equation}

* Footnotes

[fn:1] Άρα εδώ φαίνεται ότι δεν έχουμε μόνο ασυμπτωτική αλλά και εκθετική
ευστάθεια/αστάθεια - ανάλογα με το πρόσημο του $\lambda_j$, όπως άλλωστε
φαίνεται και από την εξίσωση eqref:eq:3. 

