#+TITLE: Βασικά θεωρήματα και αξιώματα πιθανοτήτων
#+COURSE: PTS
#+DATE: <2022-03-11 Fri>
#+PROFESSOR: Κουγιουμτζής
#+INSTITUTION: A.U.Th

* Ανακεφαλαίωση: Μαθηματικοί τύποι δειγματοληψίας
Στις παρουσιάσεις του μαθήματος φαίνονται οι συγκεκριμένοι τύποι,
χαρακτηριζόμενοι από το αν η σειρά έχει σημασία και από το κατα πόσο είναι
/αποδεκτή/ η επανεμφάνιση κάποιου στοιχείου. Ας τους δούμε περισσότερο
\begin{align}
n^k\\
\binom{n}{k}\\
\frac{n!}{(n-k)!k!}\\
\binom{n+k-1}{k}
\end{align}

Έστω ότι έχουμε 4 κάρτες ( ξεχωριστές ) και θέλουμε να δούμε με πόσους
διαφορετικούς τρόπους μπορούμε να τις μοιράσουμε ( αν δεν ενδιαφερόμαστε για την
σειρά τους)

*** Κάθε τρόπο που μπορούμε να τις μοιράσουμε:
Αυτό θα ήταν το δυναμοσύνολο που συναντήσαμε στην προηγούμενη διάλεξη άρα
$2^n=2^4=16$ πιθανές διαφορετικές μορφές.

Εστιάζουμε όμως, για να φανεί η χρησιμότητα των παραπάνω τύπων, στις πιθανές
τριάδες που μπορούν να σχηματιστούν:
*** Με διάταξη και επανάθεση
Αν στις τριάδες που θα φτιάξουμε μπορούμε να έχουμε την ίδια κάρτα σε δύο θέσεις
( μάλλον άστοχη η επιλογή του παραδείγματος, μα και πάλι ), οι πιθανοί
συνδυασμοί που μπορούν να προκύψουν είναι:
|   1 |   1 |   1 |
|   1 |   1 |   2 |
|   1 |   1 |   3 |
| ... | ... | ... |
|   4 |   4 |   4 |

Το πλήθος των οποίων δίνεται από την:
\begin{equation}
n^k
\end{equation}

**** Παρατήρηση:
Το συγκεκριμένο είναι εύκολο να /προκύψει/ και από κάποιον που έχει έστω βασικές
γνώσεις προγραμματισμού και μέσω της πολυπλοκότητας nested loops, καθώς
υπολογίζεις *κάθε πιθανή μορφή* - brute-forcing.

*** Με διάταξη χωρίς επανάθεση
Αν όμως δεν μπορούμε να χρησιμοποιήσουμε μια κάρτα παραπάνω από μια φορές τότε
αλλάζει εντελώς ο τύπος. Αυτό είναι εύκολα κατανοητό. Στις $n$ κάρτες, μπορούμε
να επιλέξουμε $n$, ενώ αφαιρώντας μια, την επόμενη θέση μπορούν να πάρουν $n-1$,
$n-2$, ..., $n-k+1$ κάρτες. Εξού και ο τύπος:
\begin{equation}
n(n-1)(n-2)(n-\cdots)(n-k+1)
\end{equation}

**** Παράδειγμα: Πρόεδρος, ταμίας γραμματέας
Επιλέγω τον πρόεδρο και κατόπιν επιλέγω τα υπόλοιπα μέλη του συμβουλίου:
Είναι $k = 3, n = 25$, όπου $n$ ο υποτιθέμενος αριθμός των υποψηφίων:

Οι περιπτώσεις δίνονται από την:
\begin{equation}
25(25-1)(25-2) = 25\cdot 24 \cdot 23 = 13800
\end{equation}
*** Χωρις διάταξη, με επανάθεση
Δεν το έχω ξεκαθαρίσει αρκετά στο μυαλό μου - με κάποιο παράδειγμα: Είναι απλά
ένας τύπος.
\begin{equation}
\binom{n+k-1}{k}
\end{equation}

**** Ισοδύναμη έκφραση
Με πόσους τρόπους μπορούμε να βάλουμε $k$ πανομοιότυπα στοιχεία σε $n$ κουτία

*** Χωρίς διάταξη, χωρίς επανάθεση
Να χωρίσουμε τα $n$ στοιχεία ανά $k$ στοιχεία. Η σειρά δεν μας νοιάζει, μα
προφανώς, δεν μπορούμε να τα επαναχρησιμοποιήσουμε.
\begin{equation}
\binom{n}{k}
\end{equation}

**** Κάρτες και full house
Θέλουμε να υπολογίσουμε τις πιθανότητες κάποιος να έχει full house.

Χωρίζουμε τις επιμέρους έννοιες:
- Έστω αρχικά οι πιθανοί συνδυασμοί έτσι ώστε να καταλήξουμε με μια τριάδα εκ
  των ίδιων φύλλων: $\binom{4}{3}$
  Αυτό συμβαίνει γιατί για κάθε τύπο φύλλου ( άσσους, δυάρια, τριάρια κτλ )
  θέλουμε όλους τους τρόπους _χωρίς επανάθεση_ που μπορεί να υπάρξει τριάδα
  Έτσι οι περιπτώσεις να αποκτήσουμε τριάδα δίνονταί από την
\begin{equation}
A = \text{triplet} = 13 * \binom{4}{3}
\end{equation}
- Τώρα θέλουμε να υπολογίσουμε την πιθανότητα να έχουμε και δυάδα από κάποιο εκ
  των υπολοιπόμενων φύλλων: $( 13 - 1  = 12 )$
  Άρα το δεύτερο συμβάν που θέλουμε να λάβει χώρα είναι το $B$, το οποίο δίνεται
  /περιγράφεται/ από την:
\begin{equation}
B = \text{pair} = 12 \binom{4}{2}
\end{equation}

Το επόμενο λογικό βήμα είναι να υπολογίσουμε τις πιθανότητες να συμβούν τα $A,B$
*ταυτόχρονα*, το οποίο είναι άλλωστε και το ζητούμενο:
\begin{align*}
\prod = \frac{A\times B}{\binom{52}{5}} = \frac{13\binom{4}{3}\times12\binom{4}{2}}{\binom{52}{5}}
\end{align*}


** Ταυτότητες
\begin{align*}
\binom{n}{k} &= \binom{n}{n-k} = \frac{n!}{(n-k)!k!}\\
n\binom{n-1}{k-1} &= k\binom{n}{k} \\
\binom{m+n}{k} &= \sum_{j=0}^k\binom{m}{j}\binom{n}{k-j} &\text{Vandermonde}
\end{align*}

** Παραδείγματα
*** Ρίψεις νομίσματος ( Bose-Einstein )
Έστω ότι ρίχνουμε το ίδιο νόμισμα δύο φορές. Οπότε έχουμε $A= \text{2 coin
flips}$.
- Ο τύπος $n^k$ μας δίνει $4$ καθώς έχουμε
  | K  | K |
  | Γ  | Γ |
  | Κ  | Γ |
  | Γ  | Κ |
- Όμως, αν δεν ξεχωρίζουμε μεταξύ των ΚΓ και ΓΚ, ο τύπος $\binom{n+k-1}{k}$
  είναι προφανώς καλύτερος, αφού συμπυκνώνει εκείνες τις δύο πιθανότητες σε μία,
  δίνοντας μας 3.
* Εννοια της πιθανότητας
Στην προηγούμενη ενότητα είδαμε την έννοια του δειγματοχώρου ( sample space ),
$S$. Έστω τώρα ένα σύνολο γεγονότων (δειγματοσημείων) που θέλουμε να συμβούν
$A$. Ορίζουμε την πιθανότητα να συμβεί το $A$ ως το πηλίκο του πλήθους των
στοιχείων του $A$ με το πλήθος δυνατών δειγματοσημείων.
\begin{equation}
P(A) = \frac{\text{number of desired sample points}}{\text{number of possible sample points}}
\end{equation}
*** Παράδειγμα:
Έστω σε μία μάντρα αυτοκινήτων 8 χαλασμένα αυτοκίνητα, στα 20 συνολικά.
Επιλέγονται τυχαία 4 για έλεγχο. Ποια είναι η πιθανότητα να επιλεγεί μόνο 1
ελαττωματικό:
Ορίζω ως $A = \text{only one faulty car}$
\begin{align*}
P(A) = \frac{\binom{8}{1}\binom{12}{3}}{\binom{20}{4}} = \cdots = \frac{220}{4845} =  0.0454 \approx 4.5%
\end{align*}

Πως το υπολογίσαμε:
1. Βρήκαμε το πλήθος των περιπτώσεων που μας έδιναν μόνο ένα χαλασμένο
   αυτοκίνητο, χωρίζοντας το στην /συλλογή/ από τα δύο ξεχωριστά υποσύνολα
   αυτοκινήτων ( εκείνα που λειτουργούσαν και εκείνα που δεν λειτουργούσαν ).
2. Βρήκαμε το πλήθος όλων των περιπτώσεων επιλογής 4 αυτοκινήτων
3. Εφαρμόσαμε των τύπο της πιθανότητας
** Πρόβλημα γενεθλίων
Επανερχόμαστε στο πρόβλημα των γενεθλίων που αναφέρθηκε και στις σημειώσεις της
πρώτης διάλεξης. Ποια είναι η πιθανότητα από τα $n$ άτομα να υπάρχουν
τουλάχιστον 2 άτομα που να έχουν γενέθλια την ίδια μέρα.

Αρχικά, θα χρειαστεί να /επαναπροσδιορίσουμε/ το πρόβλημα, θέτοντας μερικούς κανόνες:
1. /Βγάζουμε/ την 29η Φεβροθαρίου
2. /Ανεξαρτησία γενεθλίων/
   Τα γενέθλια όλων είναι ανεξάρτητα μεταξύ τους

$A = \{ \text{2 out of K have birthday on the same day} \}$

Είναι δύσκολο να προσεγγίσουμε το πρόβλημα ως προς το $A$. Αντ' αυτού μπορούμε
να το προσεγγίσουμε ως προς $\bar{A}$ και κατόπιν να εφαρμόσουμε την $1 = P(A) +
P(\bar{A})$:

Επομένως:
\begin{equation}
P(\bar{A}) = \frac{365\cdot364\cdots (366-k)}{365^k}
\end{equation}

Αναλύοντας λίγο περισσότερο αυτόν τον τύπο:
- Αριθμητής:
  Πλήθος υποσυνόλων $k$ εκ των $365$ στοιχείων, χωρίς επανάθεση, μα με διάταξη.
  Η αλήθεια είναι πως δεν καταλαβαίνω γιατί χρησιμοποιήθηκε το συγκεκριμένο
  παρόλο που από μαθηματικής άποψης βγάζει νόημα. Το /με διάταξη/ με χαλάει.
- Παρονομαστής:
  Όλες οι πιθανές, με διάταξη και επανάθεση περιπτώσεις:

Καθώς, όπως άλλωστε αναφέρθηκε και προηγουμένως, $P(A) = 1 - P(\bar{A})$ έχουμε:
\begin{equation}
P(A) =
\begin{cases}
50.7\% &k=23\\
97\% &k=50\\
99.99\% &k=100
\end{cases}
\end{equation}

Το οποίο δείχνει ότι ήδη για $k \geq 23$ είναι πιο πιθανό να συμπίπτουν τα
γενέθλια μελών του κοινού από ότι το να μη συμβαίνει.

** Αξιώματα πιθανότητας Kolmogorov για πεπερασμένο δειγματοχώρο
Ο χώρος πιθανοτήτων αποτελείται από τον δειγματοχώρο $S$ και την συνάρτηση $P: A
\subseteq S$, για την οποία ισχύουν τα παρακάτω:
  1. $0\leq P(A)\leq 1$
  2. $P(S) = 1$
  3. Αν $A,B$ ξένα μεταξύ τους: $P(A\cup B) = P(A)+P(B)$
** Βασικά θεωρήματα πιθανότητας
1. $P(\emptyset)=0$
2. $P(A)=1-P(\bar{A})$
3. $A\subseteq B \Rightarrow P(A)\leq P(B)$
4. $P(B-A) = P(B) - P(A\cap B)$
5. $P(B\cup A) = P(A)+P(B) -P(A\cap B)$
They have been added twice, one could think of it in the same way as
\begin{equation}
\cos{x} = \frac{e^{\jmath x}+e^{-\jmath x}}{2}
\end{equation}

* Footnotes

[fn:1]  Η απόδειξη της ισότητας υπάρχει και στις διαφάνειες της προηγούμενης διάλεξης.
