#+title: A.U.Th Notes
#+HTML_LINK_UP: ../index.html
#+options: toc:nil

Οι σημειώσεις μου δεν είναι κάτι το στατικό. Συνεχώς προσπαθώ να τις βελτιώνω,
όπως βελτιώνεται η κατανόηση μου για το αντικείμενο που καλύπτουν,
περιοριζόμενος, όμως, σαφέστατα από τον χρόνο. Αν κάποιος βρει λάθη ή ελλείψεις
βλέποντας τες, τυχόν βελτιώσεις με την μορφή PR στο Github ή με σχόλιο στην
αντίστοιχη διάλεξη, είναι ευπρόσδεκτες.

Ακόμα, σε πολλά μαθήματα οι σημειώσεις θα λείπουν. Σε αυτή την περίπτωση, με
εξαίρεση αρκετές διαλέξεις του δεύτερου έτους, οι οποίες είναι κάπως δύσκολο να
δημοσιοποιηθούν λόγω έλλειψης χρόνου (ίσως και ενδιαφέροντος την παρούσα χρονική
στιγμή), δείχνουν κατα πάσα πιθανότητα, πως για εκείνα τα μαθήματα δεν κράτησα
(με αυτόν τον τρόπο) σημειώσεις.



* 2ο Έτος
- [[file:em1/index.org][ΕΜ1: Εφαρμοσμένα Μαθηματικά 1]]
- [[file:el1/index.org][EL1: Ηλεκτρονική 1]]
- [[file:pts/index.org][PTS: Θεωρία Πιθανοτήτων και Στατιστική]]

* 3ο Έτος
Χειμερινό Εξάμηνο
- [[file:ssd/index.org][SSD: Στοχαστικά Σήματα και Διαδικασίες]]
- [[file:tlp1/index.org][TLP1: Τηλεπικοινωνιακά Συστήματα 1]]
- [[file:sae1/index.org][SAE1: Συστήματα Αυτόματου Ελέγχου 1]]

Εαρινό Εξάμηνο
- [[file:tlp2/index.org][TLP2: Τηλεπικοινωνιακά Συστήματα 2]]
- [[file:cn1/index.org][CN1: Δίκτυα Υπολογιστών 1]]
- [[file:sae2/index.org][SAE2: Συστήματα Αυτομάτου Ελέγχου 2]]
