#+TITLE: With (More Than) A Little Help From My friends
#+DATE: <2022-04-01 Fri>

Αν μου έλεγε κανείς ποτέ πως όταν, επιτέλους, θα αποφάσιζα να φτιάξω και να
/συντηρώ/[fn:1] την δική μου ιστοσελίδα, θα την χρησιμοποιούσα για να γράψω το
συγκεκριμένο άρθρο μάλλον θα γέλαγα. Θα το καταλάβαινα μα παρόλα αυτά θα γέλαγα.

Αυτό το άρθρο είναι σαν /φόρος τιμής/ για όλους εκείνους τους φίλους που θεωρώ
κολλητούς μου και που θα έκανα τα πάντα για εκείνους, παρόλα αυτά φαίνεται σαν
να έχω ξεχάσει και να μη δίνω σημασία. Είναι για όλους εκείνους τους φίλους, που
όταν καταφέρνω και τους κάνω να χαμογελάσουν ή όταν σπάνια, και αλήθεια λυπάμαι
για αυτό, φαίνομαι χρήσιμος και τους βοηθάω, νιώθω τον κόσμο να είναι ένα πολύ
πιο χαρούμενο μέρος. Είναι για τους φίλους που ποτέ δεν έμαθαν οτι τους θεωρώ
φίλους μου, ούτε το πόσο σημαντικοί είναι για μένα γιατί... /άνθρωποι/: Μερικές
φορές κρατάμε κακία και ηλίθιους τύπους αντί να είμαστε καλοί και ο εαυτός μας.
Είναι για όλους με τους οποίους μάλωσα ξανά και ξανά και ξανά, και όμως τώρα δεν
μπορώ να θυμηθώ ούτε μια φορά που φωνάξαμε ούτε μια φορά που να μη γελάγαμε
μαζί. Είναι για όλους εκείνους με τους οποίους έχτισα τόσο όμορφες και ζεστές
αναμνήσεις.

Σας ευχαριστώ πάρα πολύ. Και λυπάμαι που δεν είμαι καλύτερος φίλος. Λυπάμαι που
δεν βγαίνω έξω μαζί σας όλη την ώρα να σας το δείχνω. Λυπάμαι που αυτά τα λόγια
αν/θα τα διαβάσετε μέσα απο μία οθόνη αντί να τα ακούσετε απο μένα σε κάποια
βόλτα. Απλά ήθελα να ξέρετε πως και αν και έχω τις δικές μου βλακείες και
ιδαιτερότητες - τις τύψεις και τις αηδίες - είμαι πάντα εδώ για σας.

* Footnotes

[fn:1] Έστω με τον τρόπο που το κάνω, με τις βιαστικές σημειώσεις, review, και ιδέες
