#+TITLE: Procrastination / Anxiety: A strange way of doing nothing
#+DATE: <2023-11-23 01:39>
#+DESCRIPTION: Ah, just what life feels like sometimes.
#+FILETAGS: philosophy idea 

If someone pays attention at the time this article was written, it
will become even more evident that it is not just another day for me.
Neither is this just another article, because in it I have tried to
capture the essence of something that has been bothering me for quite
some time.

*Embarking on a task with the intention of mastering it is one thing; tackling it under the pressure of a deadline is an entirely different challenge.*

I had started working on a project for my university course on
Parallel and Distributed Systems, a subject I have come to
tremendously appreciate, when for personal (and as it happens academic
reasons), I got a little bit sidetracked. At that point, what I had
started working on with joy and satisfaction[fn:1] turned to be a
brand new source of stress and disappointment.

The strangest thing is not that I saw my efficiency drop, because at
the end of the day, this happens. (un)Fortunately, we are not, and
hopefully we will never be, machines, so our emotions can have a toll
on us. What troubles me the most is *not focusing on that specific
task (mentally) prevented me from doing anything else wholeheartedly*.

This, extremely short article, is for anyone that might find
themselves feeling that way: *If you can't avoid it, deal with it.*
It certainly does not seem as simple that moment, but in hindsight,
there is not much more to it. Maybe start by doing something you
prefer, but avoid staying inactive.

* Footnotes

[fn:1] I really wish that the greek word *meraki* was gradually accepted
into the English language. I would have loved using it in this
context, and I believe that the philosophy and calmness behind it is
something widely sought for. 
