#+TITLE: On this site's design
# #+DATE: <2023-06-11 01:19>
#+DATE: <2024-01-22 Mon>
#+DESCRIPTION: 
#+FILETAGS: blog

I have devoted way more time than I would like to admit, thinking of
how this blog looks and behaves[fn:1]. It is simple, smooth and minimal,
just like I wanted it to be, yet I can not stop thinking that it does
not feel that way: It feels more like a remnant of the past[fn:2].

It definitely stands out from the norm, embracing a /less is more/
philosophy, implemented through the absence of images and vibrant
visuals. I am extremely proud of that, not only because of its
practicality, but because of its subjective timelessness.

Fonts really matter and I think that picking this one last year change
completely changed the look of the site. It is a welcome change,
because this one was actually the only thing I wanted to change for
some time but never got around to doing.

At the end of the day, it does not matter if a site does not have
vibrant images for every post, or if the plain text format does not
really allow for emojis to put some more color. It is beautiful as it
is.

After all, we're chasing simplicity.

* Footnotes
[fn:2] And it is, a tribute to older computer forums and websites, to
people and groups that inspired me both as a computer geek and as
someone interested in keeping safe all that warrants protection.

[fn:1] Sadly, I spent much of that time thinking of what other people,
especially in the tech field might say of such a brutal and
minimalistic blog, without many of the features already present in
other personal websites I've seen...   
