#+TITLE: Future of personal computers
#+DATE: <2023-04-12 13:29>
#+DESCRIPTION: 
#+FILETAGS: essay

#+begin_note
Actual finalization date is <2023-09-20 Wed>. 
#+end_note

I was just thinking how strange our times are. Everything is so
rapidly changing and what seems only logical to happen next feels like
an absurdity of our imagination. For example ... computers.

We have gotten used to having a computer next to us to work on, but it
often is a mere illusion: even at the moment of writing, many people
work on remote computers.

If it is already happening, what am I thinking of? Simply the extend
to which this can dominate personal computing.

As someone that has gone far and wide (unfortunately) numerous times
to create  his ideal working environment, I am deeply intrigued by the
potential effect that the high QoS in modern networking may have in
personal (and professional) computing. Make something once, and always
work on it: No more searching for files between computers. No more,
having a cloud service to sync your files between different computers.
No more setting your applications up on each one. No more, no more.

/Going back to a mainframe model/, one may opt to always connect to a
specific machine (it does not even need to be physical - obviously),
from all of their devices. There are some technical difficulties and
lots of security challenges, but undoubtedly, we're heading that way.

Just like NVIDIA, and other companies I may not be aware of, tried
with gaming: to have a base-level device streaming high quality
content through the Internet, allowing the users to overcome the
limitations of their handheld device, this can happen one a much
larger scale.

After all, this could be revolutionizing, slashing the need to have
many highly capable devices, but replacing those with (barely
functional - compared to the high end ones I suppose) ones that only
serve as the monitor and the other peripherals.

However, obviously danger is around the corner ("μηδέν καλόν αμιγές
κακού"). 

#+caption: Some advantages and disadvantages to the /mainframe/ model
| Advantages                                                                        | Disadvantages                                         |
|-----------------------------------------------------------------------------------+-------------------------------------------------------|
| Easier to maintain                                                                | More difficult to set up                              |
| All files at one place                                                            | Inherently more challenging to secure                 |
| Only one machine needs to be upgraded every now and then - /peripherals/ may remain | /Mainframe/ requires more computing power               |
|                                                                                   | Prone to subscription model (and all that it entails) |
|                                                                                   |                                                       |


This last disadvantage, the dystopic thought that made me think of
this /mainframe/ model, is from my point of view, rather crucial.
Especially since everything around us seems to be moving at the speed
of light towards a subscription based / own-nothing model.

Although the advantages are by no means insignificant, it is vital
that the subscription model does not eliminate /traditional/ computing.
I can only imagine the freedom of speech, privacy, availability,
financial and so on concerns of *having to depend* on a
(not-always-trusty) third party to host your computer.

I may develop on the inherent dangers of the domination of the
subscription based model to the world. The lack of regulation and talk
around it is troubling.

To personal computing
#+begin_quote
Just stick around cause we will miss you
#+end_quote
