#+TITLE: Greek folk wisdom
#+DATE: <2024-09-23 00:38>
#+DESCRIPTION: 
#+FILETAGS:

* Introduction
Sometimes an article or a book can deliver a great mental punch in
impressively few words, and that is by itself fascinating. This
captivating sensation is something I have repeatedly encountered when
people in a conversation use a quote found in my home country's[fn:1]
folk wisdom... Especially when it is something I /believed yet had
never put in words/.

#+NAME: On this article
#+begin_note
I do not think this article will ever be complete. In fact, it might
be closer to a list than an article; A list of quotes[fn:2] with short descriptions.
#+end_note

Στην εποχή της υπερκατανάλωσης της πληροφορίας νιώθω πως είναι κρίμα
όποτε μαθαίνω κάποιο καινούριο γνωμικό: γιατί δεν το έμαθα νωρίτερα;
Τόσα άλλα τα είδα νωρίτερα... Και κατα κάποιο βαθμό, όσο αστείο και να
φανεί, φοβάμαι μην αυτά χαθούν, γιατί η συλλογική σοφία που περιέχουν,
αν και δεν /ξεκλειδώνει/ σε μία στιγμή διαβάζοντας τα, είναι ίσως η
αγαπημένη μου μορφή φιλοσοφίας: πρακτική.

Αν τυχόν το διαβάσει κάποιος αυτό, μου ήταν παράξενο το να γράφω στα
αγγλικά[fn:3], αλλά σκέφτηκα πως είναι αρκετές οι φορές που έχω δει
κάποιο ξένο γνωμικό και να το έχω ενστερνιστεί, κατα κανόνα επειδή
αυτό ήταν διαθέσιμο και στα αγγλικά. Οπότε, θέλησα να το γράψω έτσι.

* Γνωμικά

** Η φτήνια τρώει τον παρά                                                               :noexport:
** Αγάλι αγάλι γίνεται η αγουρίδα μέλι                                                   :noexport:
** Κάθε πράγμα στον καιρό του και ο κολιός τον Αύγουστο                                  :noexport:
** Εφτού που είσαι ήμουνα και δω που είμαι θα ‘ρθεις.
** Ρόδα είναι και γυρίζει
** Τρώει η σκουριά το σίδερο και η θλίψη την καρδιά μας.
** Όποιος δεν θέλει να ζυμώσει, δέκα μέρες κοσκινίζει.
** Το σήμερα είναι του Θεού, το αύριο του πονηρού.
** Κάλλιο αργά παρά ποτέ.
** Όποιος βιάζεται σκοντάφτει.
** Ένας κούκος δεν φέρνει την άνοιξη.
** Ο βρεγμένος τη βροχή δεν τη φοβάται.
** Καθαρός ουρανός αστραπές δε φοβάται.
** Μαθημένα τα βουνά απ’ τα χιόνια.
** Της νύχτας τη δουλειά τη βλέπει η μέρα και γελά.
** Όταν λείπει η γάτα, χορεύουν τα ποντίκια.
** Ο λύκος κι αν εγέρασε κι άσπρισε το μαλλί του, ούτε τη γνώμη άλλαξε ούτε την κεφαλή του.
** Κάλλιο να σου βγει το μάτι παρά το όνομα.
** Το πρόβατο το μοναχό, εκείνο τρώει ο λύκος.
** Τα ράσα δεν κάνουν τον παπά.
** Μπρος τα κάλλη τι είναι ο πόνος.
** Κάλλιο κακή φτιάσις παρά κακή κράσις.
** Δείξε μου το φίλο σου, να σου πω ποιος είσαι.
** Μεταξύ κατεργαραίων, ειλικρίνεια.
** Έμαθε ξεβράκωτος και ντρέπεται ντυμένος.
* Footnotes

[fn:3] Και στα ελληνικά δηλαδή για το συγκεκριμένο άρθρο, γνωρίζοντας
πολύ καλά πως υπάρχουν πολύ καλύτεροι χρήστες της γλώσσας για την
ερμηνεία των ρητών μας. 

[fn:2] The quotes themselves might often be attributed to a real
person, yet they are ingrained in the Greek language.

[fn:1] Obviously, one often meets such quotes in other civilizations
and that is the beautiful part of humanity. Just think of the fact
that there are numerous times where people who could have never
possibly met reached the same conclusions!
