#+TITLE: About
#+DATE: 
#+DESCRIPTION: My name is Lamprinos Chatziioannou and welcome to my personal website. Currently an undergraduate student in the School of Electrical and Computer Engineering at A.U.Th, I balance my academic pursuits with a role as a Network Engineer Intern at my campus' Network Operations Center (NOC).
#+OPTIONS: toc:nil
#+FILETAGS: index 

H3!10 w0R1d! My name is Lamprinos Chatziioannou and welcome to my
personal website. Since you have visited the ~/about~ page, I suppose
you would like to learn something more about me... We have something
in common :P

Currently an undergraduate student in the School of Electrical and
Computer Engineering at A.U.Th, I balance my academic pursuits with a
role as a Network Engineer Intern at my campus' Network Operations
Center (NOC). This position allows me to apply the theoretical
knowledge gained from my studies in a practical, real-world context,
providing a comprehensive understanding of network systems and
infrastructure.

My journey into the wonderful world of computers has been going on for
quite some time now, first getting into coding back in junior high
school. Always committed to growth and learning, and lucky enough to
have had quite some mentors and good friends through the years, I take
pride in trying to give back to the community, whenever I can.

In the last couple of years, I obtained my Cisco Certified Network
Associate (CCNA) certification, started this blog, with a desire to
both document my progress but also share my findings with the world,
and put my little (too little) stone to the huge mountain open-source
programs and innovations, by publishing my two /loyal/ emacs packages:
[[https://github.com/chatziiola/org-lectures][org-lectures]] and [[https://github.com/chatziiola/klp][klp]].

Beyond the realm of academia and work, cybersecurity stands out as a
key area of interest for me—a field I am deeply passionate about and
hope to someday contribute seriously to. In fact, most of my articles
here, as one can easily see, are centered around cybersec!

As I forge ahead, I remain open to new experiences and opportunities.

* Skills
I generally prefer to stay away from specific technologies but instead
build strong foundations so that I can use whatever tools at my
disposal to get the job done. As such, this list is consciously kept
small, avoiding numerous tools that I could use if needed yet I do not
consider so important.

# Powered by shields.io (had also considered https://simpleicons.org/,
# before settling, turns out shields uses simpleicons in a simpler way)
#+begin_export html
<div class="skilliconscontainer">
<a href="https://www.mysql.com/doc/" target="_blank"><img src="https://img.shields.io/badge/SQL-4479A1?style=flat&logo=mysql&logoColor=white" class="skillicon" alt="SQL Icon"/></a>
<a href="https://en.wikipedia.org/wiki/C_(programming_language)" target="_blank"><img src="https://img.shields.io/badge/C-00599C?style=flat&logo=c&logoColor=white" class="skillicon" alt="C Icon"/></a>
<a href="https://en.wikipedia.org/wiki/C%2B%2B" target="_blank"><img src="https://img.shields.io/badge/C%2B%2B-00599C?style=flat&logo=c%2B%2B&logoColor=white" class="skillicon" alt="C++ Icon"/></a>
<a href="https://developer.arm.com/documentation" target="_blank"><img src="https://img.shields.io/badge/ARM-00599C?style=flat&logo=arm&logoColor=white" class="skillicon" alt="ARM Assembly Icon"/></a>
<a href="https://www.python.org/doc/" target="_blank"><img src="https://img.shields.io/badge/Python-3776AB?style=flat&logo=python&logoColor=white" class="skillicon" alt="Python Icon"/></a>
<a href="https://www.gnu.org/software/bash/manual/" target="_blank"><img src="https://img.shields.io/badge/Bash-4EAA25?style=flat&logo=gnubash&logoColor=white" class="skillicon" alt="Bash Icon"/></a>
<a href="https://git-scm.com/doc" target="_blank"><img src="https://img.shields.io/badge/Git-F05032?style=flat&logo=git&logoColor=white" class="skillicon" alt="Git Icon"/></a>
<a href="https://docs.ansible.com/" target="_blank"><img src="https://img.shields.io/badge/Ansible-EE0000?style=flat&logo=ansible&logoColor=white" class="skillicon" alt="Ansible Icon"/></a>
<a href="https://www.kernel.org/doc/html/latest/" target="_blank"><img src="https://img.shields.io/badge/Linux-FCC624?style=flat&logo=linux&logoColor=black" class="skillicon" alt="Linux Icon"/></a>
</div>
#+end_export

* Projects                                                                                :noexport:

** Academic
1. Structured Programming - 1st Semester
   - https://github.com/chatziiola/sailing-game
2. Object-Oriented Programming - 2nd Semester
   - https://github.com/chatziiola/themis-battleship
3. Algorithm Design and Analysis - 6th Semester
   - https://github.com/chatziiola/ada_projects/blob/master/ada_ergasia-1.pdf
4. Computer Networks I - 6th Semester
   - no project was submitted on my part
5. Operating Systems - 7th Semester
   - [ ] Merge the two
   - https://github.com/chatziiola/ece-auth_oss
   - https://github.com/chatziiola/GitHashingExercise
6. Computer Network Security - 
   - https://github.com/chatziiola/csd_cns
7. Low Level HW Digital Systems I - 7th Semester
   - uncompleted
8. Low Level HW Digital Systems II - 8th Semester
   - uncompleted
9. Microprocessors and Peripherals - 8th Semester
   - https://github.com/chatziiola/mp-arm-labs


** Personal
1. Ansible macos/arch configuration
2. This blog
   - [ ] walkhthrough's writeups
