#+TITLE: About
#+SUBTITLE: Alright Alright Alright!
#+DESCRIPTION: I'm Lamprinos Chatziioannou, and this is my personal website, where I share CTF write-ups, ideas, and anything else that catches my interest! :P
#+OPTIONS: toc:nil
#+FILETAGS: index 

* H3!10 w0R1d! 
My name is Lamprinos Chatziioannou and welcome to my personal website.
Since you have visited the ~/about~ page, I suppose you would like to
learn something more about me... We have something in common :P

Currently an undergraduate student in the School of Electrical and
Computer Engineering at A.U.Th, I balance my academic pursuits with a
role as a Network Engineer Intern at my campus' Network Operations
Center (NOC). This position allows me to apply the theoretical
knowledge gained from my studies in a practical, real-world context,
providing a comprehensive understanding of network systems and
infrastructure.

My journey into the wonderful world of computers has been going on for
quite some time now, first getting into coding back in junior high
school. Always committed to growth and learning, and lucky enough to
have had quite some mentors and good friends through the years, I take
pride in trying to give back to the community, whenever I can.

In the last couple of years, I obtained my Cisco Certified Network
Associate (CCNA) certification, started this blog, with a desire to
both document my progress but also share my findings with the world,
and put my little (too little) stone to the huge mountain open-source
programs and innovations, by publishing my two /loyal/ emacs packages:
[[https://github.com/chatziiola/org-lectures][org-lectures]] and [[https://github.com/chatziiola/klp][klp]].

Beyond the realm of academia and work, cybersecurity stands out as a
key area of interest for me—a field I am deeply passionate about and
hope to someday contribute seriously to. In fact, most of my articles
here, as one can easily see, are centered around cybersec!

As I forge ahead, I remain open to new experiences and opportunities.

# Present for a long time in my Github bio and I still like it very much
#+begin_quote
Cyberspace consists of transactions, relationships, and thought
itself, arrayed like a standing wave in the web of our communications.
Ours is a world that is both everywhere and nowhere, but it is not
where bodies live. We are creating a world that all may enter without
privilege or prejudice accorded by race, economic power, military
force, or station of birth. We are creating a world where anyone,
anywhere may express his or her beliefs, no matter how singular,
without fear of being coerced into silence or conformity.
#+end_quote

* Skills
I generally prefer to stay away from specific technologies but instead
build strong foundations so that I can use whatever tools at my
disposal to get the job done. As such, this list is consciously kept
small, avoiding numerous tools that I could use if needed yet I do not
consider so important.

# Powered by shields.io (had also considered https://simpleicons.org/,
# before settling, turns out shields uses simpleicons in a simpler way)
#+begin_export html
<style>
.skilliconscontainer {padding-top: 1em; text-align: center;}
.skillicon{display: inline; transform: none; transition: none;}
</style>

<div class="skilliconscontainer">

<a href="https://www.mysql.com/doc/" target="_blank"><img src="https://img.shields.io/badge/SQL-4479A1?style=flat&logo=mysql&logoColor=white" class="skillicon" alt="SQL Icon"/></a>
<a href="https://en.wikipedia.org/wiki/C_(programming_language)" target="_blank"><img src="https://img.shields.io/badge/C-00599C?style=flat&logo=c&logoColor=white" class="skillicon" alt="C Icon"/></a>
<a href="https://en.wikipedia.org/wiki/C%2B%2B" target="_blank"><img src="https://img.shields.io/badge/C%2B%2B-00599C?style=flat&logo=c%2B%2B&logoColor=white" class="skillicon" alt="C++ Icon"/></a>
<a href="https://developer.arm.com/documentation" target="_blank"><img src="https://img.shields.io/badge/ARM-00599C?style=flat&logo=arm&logoColor=white" class="skillicon" alt="ARM Assembly Icon"/></a>
<a href="https://www.python.org/doc/" target="_blank"><img src="https://img.shields.io/badge/Python-3776AB?style=flat&logo=python&logoColor=white" class="skillicon" alt="Python Icon"/></a>
<a href="https://www.gnu.org/software/bash/manual/" target="_blank"><img src="https://img.shields.io/badge/Bash-4EAA25?style=flat&logo=gnubash&logoColor=white" class="skillicon" alt="Bash Icon"/></a>
<a href="https://git-scm.com/doc" target="_blank"><img src="https://img.shields.io/badge/Git-F05032?style=flat&logo=git&logoColor=white" class="skillicon" alt="Git Icon"/></a>
<a href="https://docs.ansible.com/" target="_blank"><img src="https://img.shields.io/badge/Ansible-EE0000?style=flat&logo=ansible&logoColor=white" class="skillicon" alt="Ansible Icon"/></a>
<a href="https://www.kernel.org/doc/html/latest/" target="_blank"><img src="https://img.shields.io/badge/Linux-FCC624?style=flat&logo=linux&logoColor=black" class="skillicon" alt="Linux Icon"/></a>
<a href="https://docs.arduino.cc/" target="_blank"> <img src="https://img.shields.io/badge/Arduino-00979D?style=flat&logo=arduino&logoColor=white" class="skillicon" alt="Arduino Icon"/> </a>
<a href="https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html" target="_blank"><img src="https://img.shields.io/badge/CCNA-1BA0D7?style=flat&logo=cisco&logoColor=white" class="skillicon" alt="CCNA Icon"/> </a>
<a href="https://www.raspberrypi.org/documentation/" target="_blank"><img src="https://img.shields.io/badge/Raspberry%20Pi-A22846?style=flat&logo=raspberrypi&logoColor=white" class="skillicon" alt="Raspberry Pi Icon"/></a>
</div>
#+end_export
# Feel like this is not developed enough to be here:
# <a href="https://docs.espressif.com/projects/esp-idf/en/latest/esp32/" target="_blank"><img src="https://img.shields.io/badge/ESP32-FF0000?style=flat&logo=espressif&logoColor=white" class="skillicon" alt="ESP32 Icon"/></a>
# <a href="https://vimhelp.org/" target="_blank"><img src="https://img.shields.io/badge/Vim-019733?style=flat&logo=vim&logoColor=white" class="skillicon" alt="Vim Icon"/></a>
# <a href="https://orgmode.org/manual/" target="_blank"><img src="https://img.shields.io/badge/Org%20Mode-77AA99?style=flat&logo=org&logoColor=white" class="skillicon" alt="Org Mode Icon"/></a>
# <a href="https://www.latex-project.org/help/documentation/" target="_blank"><img src="https://img.shields.io/badge/LaTeX-47A141?style=flat&logo=latex&logoColor=white" class="skillicon" alt="LaTeX Icon"/> </a>

* Academic Projects

- [[https://github.com/chatziiola/myctiobarka][Structured Programming (C) - 1st Semester]]
- [[https://github.com/chatziiola/ece-auth_oop][Object Oriented Programming (C++) - 2nd Semester]]
- [[https://github.com/chatziiola/ece-auth_ada][Algorithm Design and Analysis - 6th Semester]]
- [[https://github.com/chatziiola/ece-auth_oss][Operating Systems - 7th Semester]] 
- [[https://github.com/chatziiola/csd-auth_cns][Computer Network Security - on Memory Security - 7th Semester]]
- [[https://github.com/chatziiola/ece-auth_mp][Microprocessors - 8th Semester]]
- [[https://github.com/chatziiola/ece-auth_se1][Software Engineering I - 8th Semester]]

Currently active ones:
- [[https://github.com/chatziiola/ece-auth_llhw][Low Level HW Digital Systems - 9th Semester]]
- [[https://github.com/chatziiola/ece-auth_da][Data Analysis - 9th Semester]]
- [[https://github.com/chatziiola/ece-auth_ot][Optimization Techniques - 9th Semester]]
- [[https://github.com/chatziiola/ece-auth_dbs][Databases - 9th Semester]]
- [[https://github.com/chatziiola/ece-auth_cn2][Computer Networks 2 - 9th Semester]]
- [[https://github.com/chatziiola/ece-auth_aca][Advanced Computers Architecture and Accelerators - 9th Semester]]

