#+TITLE: About
#+DATE: 
#+DESCRIPTION: My name is Lamprinos Chatziioannou and welcome to my personal website. Currently an undergraduate student in the School of Electrical and Computer Engineering at A.U.Th, I balance my academic pursuits with a role as a Network Engineer Intern at my campus' Network Operations Center (NOC).
#+OPTIONS: toc:no
#+FILETAGS: index 

H3!10 w0R1d! My name is Lamprinos Chatziioannou and welcome to my
personal website. Since you have visited the ~/about~ page, I suppose
you would like to learn something more about me... We have something
in common :P

Currently an undergraduate student in the School of Electrical and
Computer Engineering at A.U.Th, I balance my academic pursuits with a
role as a Network Engineer Intern at my campus' Network Operations
Center (NOC). This position allows me to apply the theoretical
knowledge gained from my studies in a practical, real-world context,
providing a comprehensive understanding of network systems and
infrastructure.

My journey into the wonderful world of computers has been going on for
quite some time now, first getting into coding back in junior high
school. Always committed to growth and learning, and lucky enough to
have had quite some mentors and good friends through the years, I take
pride in trying to give back to the community, whenever I can.

In the last couple of years, I obtained my Cisco Certified Network
Associate (CCNA) certification, started this blog, with a desire to
both document my progress but also share my findings with the world,
and put my little (too little) stone to the huge mountain open-source
programs and innovations, by publishing my two /loyal/ emacs packages:
[[https://github.com/chatziiola/org-lectures][org-lectures]] and [[https://github.com/chatziiola/klp][klp]].

Beyond the realm of academia and work, cybersecurity stands out as a
key area of interest for me—a field I am deeply passionate about and
hope to someday contribute seriously to. In fact, most of my articles
here, as one can easily see, are centered around cybersec!

As I forge ahead, I remain open to new experiences and opportunities.

