#+TITLE: Reading List
#+DATE: <2024-05-16 12:17>
#+DESCRIPTION: 
#+FILETAGS: 

* Introduction
Being an avid reader myself I always like it when I find trustworthy
sources (books, articles, websites) with lists of material to read. I
figured that my knack for losing the wonderful reading suggestions in
depths of oblivion (my zotero collection :P),and my confidence in that
I sometimes find stuff I would like my siblings and friends to read,
were good enough reasons for me to create a special page here, just
for that:

I have opted against tedious categorization: ~ctrl+f~ might be one's
best tool

#+NAME: On the nature of my suggestions
#+begin_note
Every time I visit this page I can not help but feel a certain kind of
sadness, around the suggestions I have not made so far. There are much
more books and articles I would like there to be here, many of which
perhaps should have been the first to be placed here. The list will
never be adequately updated.
#+end_note

* Books you _have_ to read
Creating a list like this feels pretentious and nearly impossible. No
matter how hard I try, I cannot think of an effective way to avoid
omissions... 
- [[https://www.navalmanack.com/][Almanack of Naval Ravikant]]: I'm extremely grateful to Eric Jorgenson
  for compiling this book. Lots of insights and ideas, beautifully
  put together.
- [[https://www.stripe.press/poor-charlies-almanack][Poor Charlie's Almanack]]: My fascination regarding Charlie Munger's
  character is what prompted me to create this list in the first
  place, and it is not randomness that is responsible for this book
  being right after the /almanack/ of Naval... Instead of chain-reaction
  I should call this one a lollapalooza effect.
- J.R.R. Tolkien's Books:
  - [[https://en.wikipedia.org/wiki/The_Children_of_H%C3%BArin][The Children of Húrin]]: I consider this to be perhaps one of the
    greatest fiction books I have ever read. Tremendously well
    crafted.
  - The Lord of The Rings trilogy
  - The Silmarillion
  - The Hobbit
- The Count of Monte Cristo, by Alexandre Doumas
- Factfulness, by Hans and Ola Rosling: Mind-boggling book. I would
  put it next to Harari's 'Homo Deus', but much easier. Forces you to
  reevaluate some ideas.
- Surely You're Joking Mr. Feynman!,
- Outliers: The Story of Success, by Malcolm Gladwell... Found myself
  suggesting that too often to friends to not include it here.

** Books I really liked
- Bruce Schneier's Books:
  - Having added his blog in the next section, I realized that I had
    not properly added his books here (at least the ones I have spent
    some time studying): 
  - Applied Cryptography
  - Liars and Outliers
- Menn's Cult Of the Dead Cow: There's something inspiring there,
  though there is something in Menn's writing style that does not
  resonate so well with me
* Podcasts
In general, I am afraid of stating that I like a podcast because most
of them produce *so much content* that you cannot possibly listen to all
of it. Aaaaand... if you are a /picky listener/ like me, you only like
specific episodes, but you may be criticized for aligning with the
whole. I don't know... we live in strange times indeed :P:
- I have liked and repeatedly go back to some episodes in [[https://open.spotify.com/show/0XrOqvxlqQI6bmdYHuIVnr?si=881b759eaee547ad][Modern
  Wisdom]]. I think good work's been done there.

* Blogs / Articles 
- https://two-wrongs.com/ I really like Chris' blog, offering a unique
  look on a plethora of different subjects. Pleasant, yet not always
  relaxed, reading.
- [[https://www.schneier.com/][Crypto-Gram]]: Schneier's influence can not be overstated,
  and many of his are exceptionally mindblowing to me, mainly for 2
  distinct reasons:
  1. He either uses a completely different approach than the one I
     have seen/thought of, allowing for increased understanding
     through that perspective or
  2. He states something that one might have come up with themselves
     but more eloquently *also allowing* for new insight.
  Thus, I can not help, but include it here.
  - [[https://www.schneier.com/blog/archives/2024/06/rethinking-democracy-for-the-age-of-ai.html][Rethinking Democracy for the Age of AI]]
- [[http://phrack.org][phrack]]: Potentially the only http site here but... One should read
  at least some bits of it.
- [[https://notes.eatonphil.com/2024-09-23-be-someone-who-does-things.html?utm_source=danielmiessler.com&utm_medium=newsletter&utm_campaign=ul-no-452-the-new-hotness-notebooklm&_bhlid=c3f7c26b97b3f0cb7aa94e9d1248603f2ed9ac09][Be Someone Who Does Things by Phil Eaton]]
- [[https://h0mbre.github.io/]]: Nice little blog - static for some time.

* Courses
- Strang's Linear Algebra
  - This course might in fact have been the reason I started this
    blog: Being so fascinated, I just kept taking notes in LaTeX and
    building my workflow so that I could one day proud myself on not
    only knowing the material covered but ... 
- Thermodynamics lectures by Prof. David Miller
  - https://www.youtube.com/playlist?list=PLZOZfX_TaWAH3zDurz4ds7jMFzhxhfKZV
