#+TITLE: Reading List
#+DATE: <2024-05-16 12:17>
#+DESCRIPTION: 
#+FILETAGS: 

* Introduction
Being an avid reader myself I always like it when I find trustworthy
sources (books, articles, websites) with lists of material to read. I
figured that my knack for losing the wonderful reading suggestions in
depths of oblivion (my zotero collection :P),and my confidence in that
I sometimes find stuff I would like my siblings and friends to read,
were good enough reasons for me to create a special page here, just
for that:

I have opted against tedious categorization: ~ctrl+f~ might be one's
best tool

#+NAME: On the nature of my suggestions
#+begin_note
Every time I visit this page I can not help but feel a certain kind of
sadness, around the suggestions I have not made so far. There are much
more books and articles I would like there to be here, many of which
perhaps should have been the first to be placed here. The list will
never be adequately updated.
#+end_note

* Books
- [Free Online] [[https://www.navalmanack.com/][Almanack of Naval Ravikant]]
- [Free Online] [[https://www.stripe.press/poor-charlies-almanack][Poor Charlie's Almanack]]
- Bruce Schneier's Books:
  - Having added his blog in the next section, I realized that I had
    not properly added his books here (at least the ones I have spent
    some time studying): 
  - Applied Cryptography
  - Liars and Outliars
- Menn's Cult Of the Dead Cow
  - There's something inspiring there.
- The Lord of the Rings trilogy


* Podcasts
- 

* Blogs / Articles 
- https://two-wrongs.com/ I really like Chris' blog, offering a unique
  look on a plethora of different subjects. Pleasant, yet not always
  relaxed, reading.
- [[https://www.schneier.com/][Crypto-Gram]]: Schneier's influence can not be overstated,
  and many of his are exceptionally mindblowing to me, mainly for 2
  distinct reasons:
  1. He either uses a completely different approach than the one I
     have seen/thought of, allowing for increased understanding
     through that perspective or
  2. He states something that one might have come up with themselves
     but more eloquently *also allowing* for new insight.
  Thus, I can not help, but include it here.
  - [[https://www.schneier.com/blog/archives/2024/06/rethinking-democracy-for-the-age-of-ai.html][Rethinking Democracy for the Age of AI]]
- [[http://phrack.org][phrack]]: Potentially the only http site here but... One should read
  at least some bits of it.

* Courses
- Strang's Linear Algebra
  - This course might in fact have been the reason I started this
    blog: Being so fascinated, I just kept taking notes in LaTeX and
    building my workflow so that I could one day proud myself on not
    only knowing the material covered but ... 
- Thermodynamics lectures by Prof. David Miller
  - https://www.youtube.com/playlist?list=PLZOZfX_TaWAH3zDurz4ds7jMFzhxhfKZV
