#+TITLE: Archive
#+SUBTITLE: [[https://www.youtube.com/watch?v=jPWNcfrZzBE][again?!]]
#+INCLUDE: ../src/header.html export html
#+begin_export html
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20251222_getting-a-proofreader-for-my-blog.html">Never Publish a Typo Again: My AI Proofreading Setup</a><div class="sitemap-header"><span class="sitemap-date"><2025-12-22 13:45></span><span class="sitemap-tag">LLM blog prompt-engineering</span></div><span class="sitemap-description">This article explores how I'm using an AI assistant, an LLM, as a proofreader to improve my writing skills as a non-native English speaker and enhance the quality of my blog posts.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20251209_disabling-youtube-shorts.html">Disabling YouTube Shorts: An easy way</a><div class="sitemap-header"><span class="sitemap-date"><2025-12-09 23:50></span><span class="sitemap-tag">youtube, ublock, productivity, adblocking</span></div><span class="sitemap-description">How to permanently block or disable YouTube Shorts on your browser. This guide provides simple filter rules for uBlock Origin, Brave, and similar ad-blockers.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20251130_a-stupid-solution-to-a-stupid-problem.html">A stupid solution to a stupid problem</a><div class="sitemap-header"><span class="sitemap-date"><2025-11-30 21:23></span><span class="sitemap-tag">emacs blog orgmode</span></div><span class="sitemap-description">Learn how to create a robust and flexible draft management system for your Org-mode blog. This guide walks you through customizing the org-publish process with Emacs Lisp functions to gain full control over which posts are published and which remain as drafts.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/htb_rev_shatteredtablet.html">Shattered Tablet</a><div class="sitemap-header"><span class="sitemap-date"><2025-02-15 Sat></span><span class="sitemap-tag">reveng htb veryeasy</span></div><span class="sitemap-description">Walkthrough of Shattered Tabled reversing (very easy) challenge by Hack The Box</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/htb_rev_flagcasino.html">HTB: FlagCasino</a><div class="sitemap-header"><span class="sitemap-date"><2025-01-31 Fri></span><span class="sitemap-tag">reveng htb</span></div><span class="sitemap-description">Walkthrough for the very easy, reverse engineering, hack the box, challenge flag casino.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/htb_rev_crypt-of-the-undead.html">HTB: Crypt Of The Undead</a><div class="sitemap-header"><span class="sitemap-date"><2025-01-29 Wed></span><span class="sitemap-tag">reveng htb</span></div><span class="sitemap-description">Hack The Box (HtB) (very) easy reverse engineering challenge writeup: using radare2</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20250115_gitting_things_done.html">'Git'ting things done</a><div class="sitemap-header"><span class="sitemap-date"><2025-01-15 19:33></span></div><span class="sitemap-description">The proper form of a gitconfig file, and what to do when you mistakenly perform commits with wrong author details</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240709_tidying_up_images.html">Tidying up the blog</a><div class="sitemap-header"><span class="sitemap-date"><2024-07-09 13:57></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/books.html">Reading List</a><div class="sitemap-header"><span class="sitemap-date"><2024-05-16 12:17></span><span class="sitemap-tag">index</span></div><span class="sitemap-description">My personal recommendations on must-read books, insightful articles, thought-provoking blogs, and more. Curated suggestions for lifelong learners, book lovers, and curious minds.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240227_wsa_reflected_dom_xss.html">WSA: Reflected DOM XSS</a><div class="sitemap-header"><span class="sitemap-date"><2024-02-27 11:41></span><span class="sitemap-tag">xss domxss reflectedxss wsa</span></div><span class="sitemap-description">Walkthrough to WSA Lab: Reflected DOM XSS</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240227_wsa_dom_xss_in_angularjs_expression.html">WSA: DOM XSS in AngularJS expression</a><div class="sitemap-header"><span class="sitemap-date"><2024-02-27 11:21></span><span class="sitemap-tag">angularjs wsa xss domxss</span></div><span class="sitemap-description">Walkthrough to WSA lab: DOM XSS in AngularJS expression with angle brackets and double quotes HTML-encoded</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240227_wsa_dom_xss_in_select.html">WSA: DOM XSS in document.write sink using source location.search</a><div class="sitemap-header"><span class="sitemap-date"><2024-02-27 10:07></span><span class="sitemap-tag">wsa xss domxss</span></div><span class="sitemap-description">Walktrough of WSA Lab: DOM XSS in document.write sink using source location.search inside a select element</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240218_wsa_rest_of_apprentice_dom_xss.html">WSA Rest of apprentice XSS labs</a><div class="sitemap-header"><span class="sitemap-date"><2024-02-18 23:05></span><span class="sitemap-tag">xss wsa</span></div><span class="sitemap-description">Complementary writeup for three WSA labs on XSS</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240216_wsa_understanding_dom_based_xss.html">WSA: Apprentice DOM Based XSS</a><div class="sitemap-header"><span class="sitemap-date"><2024-02-16 11:27></span><span class="sitemap-tag">xss wsa</span></div><span class="sitemap-description">collection of solution to 4 dom based xss labs on Web Security Academy by PortSwigger</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240214_wsa_visible_error_based_sqli.html">WSA: Visible Error-Based SQLi</a><div class="sitemap-header"><span class="sitemap-date"><2024-02-14 22:12></span><span class="sitemap-tag">wsa sqli</span></div><span class="sitemap-description">Walkthrough of the already mentioned WSA lab by PortSwigger</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240213_wsa_blind_sql_injection_with_conditional_errors.html">WSA: Blind SQL Injection with conditional errors</a><div class="sitemap-header"><span class="sitemap-date"><2024-02-13 11:22></span><span class="sitemap-tag">wsa sqli</span></div><span class="sitemap-description">Walkthrough for the related PortSwigger Web Lab.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230611_on_this_sites_design.html">On this site's design</a><div class="sitemap-header"><span class="sitemap-date"><2024-01-22 Mon></span><span class="sitemap-tag">blog</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20240121_hackerone_ctf_challenges.html">HackerOne: CTF: Micro-CMS</a><div class="sitemap-header"><span class="sitemap-date"><2024-01-21 20:38></span><span class="sitemap-tag">hackerone</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231227_making_my_life_easier.html">Make-ing my life easier</a><div class="sitemap-header"><span class="sitemap-date"><2023-12-27 12:25></span><span class="sitemap-tag">scripting blog</span></div><span class="sitemap-description">Notes on how I migrated to Make for this website, so that I can easily preview my posts before publishing</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231227_thm_game_zone.html">THM: Game Zone</a><div class="sitemap-header"><span class="sitemap-date"><2023-12-27 08:11></span><span class="sitemap-tag">tryhackme</span></div><span class="sitemap-description">Writeup for the GameZone ctf/walkthrough room in TryHackme.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231215_sigh_hasta_la_vista_thm_skynet.html">THM: Skynet</a><div class="sitemap-header"><span class="sitemap-date"><2023-12-15 11:32></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231214_back_again_thm_hackpark.html">THM Hackpark</a><div class="sitemap-header"><span class="sitemap-date"><2023-12-14 23:58></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231205_my_first_proper_buffer_overflow.html">My first (proper?) buffer overflow</a><div class="sitemap-header"><span class="sitemap-date"><2023-12-05 13:34></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231130_thm_alfred.html">THM: Alfred</a><div class="sitemap-header"><span class="sitemap-date"><2023-11-30 14:34></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231123_procrastination_anxiety_a_strange_way_of_doing_nothing.html">Procrastination / Anxiety: A strange way of doing nothing</a><div class="sitemap-header"><span class="sitemap-date"><2023-11-23 01:39></span><span class="sitemap-tag">essay</span></div><span class="sitemap-description">Ah, just what life feels like sometimes.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231120_thm_biohazard.html">THM: Biohazard</a><div class="sitemap-header"><span class="sitemap-date"><2023-11-20 15:38></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231111_thm_boiler_ctf.html">THM: Boiler CTF</a><div class="sitemap-header"><span class="sitemap-date"><2023-11-11 19:21></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231107_thm_anonymous.html">THM: Anonymous</a><div class="sitemap-header"><span class="sitemap-date"><2023-11-07 09:50></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231106_thm_wonderland.html">THM: Wonderland</a><div class="sitemap-header"><span class="sitemap-date"><2023-11-06 23:49></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231105_thm_bounty_hacker.html">THM: Bounty Hacker</a><div class="sitemap-header"><span class="sitemap-date"><2023-11-05 21:54></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231022_thm_the_marketplace.html">THM: The Marketplace</a><div class="sitemap-header"><span class="sitemap-date"><2023-10-22 18:31></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20231021_thm_anthem.html">THM: Anthem</a><div class="sitemap-header"><span class="sitemap-date"><2023-10-21 10:30></span><span class="sitemap-tag">tryhackme</span></div><span class="sitemap-description">A beginner targeted ctf</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230527_org_roam_selective_link_insertion.html">Org-roam selective link insertion</a><div class="sitemap-header"><span class="sitemap-date"><2023-05-27 22:35></span><span class="sitemap-tag">org elisp</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230412_future_of_personal_computers.html">Future of personal computers</a><div class="sitemap-header"><span class="sitemap-date"><2023-04-12 13:29></span><span class="sitemap-tag">essay</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230406_beautiful_and_simple_pdf_latex_exports_with_org_mode.html">Beautiful and simple pdf-latex exports with org mode</a><div class="sitemap-header"><span class="sitemap-date"><2023-04-06 15:28></span><span class="sitemap-tag">emacs org</span></div><span class="sitemap-description">C'est la vie</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/sae2/lec_SAE2_20230329.html">Διάλεξη 2: Ευστάθεια με διαγωνιοποίηση</a><div class="sitemap-header"><span class="sitemap-date"><2023-03-29></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/sae2/lec_SAE2_20230317.html">Διάλεξη 5(1): Θεωρήματα Lyapunov</a><div class="sitemap-header"><span class="sitemap-date"><2023-03-17></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/cn1/lec_CN1_20230314.html">Διάλεξη (1): Υλική εξέλιξη των δικτύων.</a><div class="sitemap-header"><span class="sitemap-date"><2023-03-14></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230309_a_practical_note_taking_system.html">A practical note taking system</a><div class="sitemap-header"><span class="sitemap-date"><2023-03-09 Thu 11:47></span><span class="sitemap-tag">notetaking</span></div><span class="sitemap-description">An introduction to my note taking framework</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp2/lec_TLP2_20230306.html">Διάλεξη: Σήματα και διανύσματα (?)</a><div class="sitemap-header"><span class="sitemap-date"><2023-03-06></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230208_spending_five_minutes_to_do_something_i_could_have_done_in_ten.html">Build your script library</a><div class="sitemap-header"><span class="sitemap-date"><2023-02-08 23:53></span><span class="sitemap-tag">scripting sysad</span></div><span class="sitemap-description">Late night thought collection on improving ones relationship with  small scripts</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230110_identifying_a_lethal_mistake_after_it_happened_notetaking_edition.html">Identifying a lethal mistake - after it happened: Notetaking Edition</a><div class="sitemap-header"><span class="sitemap-date"><2023-01-10 20:41></span><span class="sitemap-tag">elisp org</span></div><span class="sitemap-description">How I lost a lecture (twice) and put the blame on me (human error) instead of pointing at the faulty part of my code.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230109_notes_literate_devops_in_emacs_and_org_mode.html">Speedrun guide to Org Mode</a><div class="sitemap-header"><span class="sitemap-date"><2023-01-09 11:34></span><span class="sitemap-tag">literateprogramming org notetaking emacs</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20230105_creating_inspirational_wallpapers_from_the_comfort_of_your_terminal.html">Creating inspirational wallpapers from the comfort of your terminal</a><div class="sitemap-header"><span class="sitemap-date"><2023-01-05 13:25></span><span class="sitemap-tag">scripting</span></div><span class="sitemap-description">Because, who does not want that!</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/em1/fourier_series.html">Σειρές Fourier</a><div class="sitemap-header"><span class="sitemap-date"><2022-12-17 Sat></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/sae1/lec_SAE1_lab2-matlab.html">2ο Εργαστήριο</a><div class="sitemap-header"><span class="sitemap-date"><2022-11-24 Thu></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/sae1/lec_SAE1_lab1-matlab.html">1ο Εργαστήριο</a><div class="sitemap-header"><span class="sitemap-date"><2022-11-24 Thu></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp1/lec_TLP1_20221107.html">Διάλεξη 7: Πολυπλεξία και Υπερετερόδυνος Δέκτης.</a><div class="sitemap-header"><span class="sitemap-date"><2022-11-07></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/ssd/lec_SSD_20221102.html">Διάλεξη 6: Μεταχηματισμοί Τυχ Μεταβλητών</a><div class="sitemap-header"><span class="sitemap-date"><2022-11-02></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp1/lec_TLP1_20221025.html">Διάλεξη 6: Διαμόρφωση γωνίας στενής και ευρείας ζώνης</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-25></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/ssd/lec_SSD_20221019.html">Διάλεξη 5: Γνωστές Κατανομές</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-19></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp1/lec_TLP1_20221017.html">Διάλεξη 5: FM,PM Εισαγωγή στην διαμόρφωση FM</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-17></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/ssd/lec_SSD_20221017.html">Διάλεξη 4: Μοντέλο Ροπών</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-17></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/sae1/lec_SAE1_20221013.html">Διάλεξη 1: Εισαγωγική και σφάλματα</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-13></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp1/lec_TLP1_20221012.html">Διάλεξη 2: ΑΜ: Σημειώσεις επί των διαφανειών.</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-12></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/ssd/lec_SSD_20221012.html">Διάλεξη 3: Κυρίως Ασκήσεις.</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-12></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp1/lec_TLP1_20221011.html">Διάλεξη 4: Ολοκλήρωση AM: Εναλλακτικές AM διαμορφώσεις.</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-11></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp1/lec_TLP1_20221010.html">Διάλεξη 3: AM: Διαμορφωτές και ασύμφωνοι αποδιαμορφωτές</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-10></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/ssd/lec_SSD_20221010.html">Διάλεξη 2: Τυχαίες μεταβλητές</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-10></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/tlp1/lec_TLP1_20221003.html">Διάλεξη: 1 Εισαγωγική</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-03></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/ssd/lec_SSD_20221003.html">Διάλεξη: 1 Εισαγωγικά</a><div class="sitemap-header"><span class="sitemap-date"><2022-10-03></span><span class="sitemap-tag">lecture</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20220903_literate_configuration_management_with_vanilla_emacs.html">Literate Configuration Management with vanilla Emacs</a><div class="sitemap-header"><span class="sitemap-date"><2022-09-03 23:56></span><span class="sitemap-tag">emacs elisp literateprogramming</span></div><span class="sitemap-description">Creating an easy way to review configs</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20220719_how_i_publish_my_static_blog_on_github_pages_using_emacs.html">How i publish my static blog on Github pages using Emacs</a><div class="sitemap-header"><span class="sitemap-date"><2022-07-19 19:26></span><span class="sitemap-tag">emacs elisp blog</span></div><span class="sitemap-description">Automating the tricky org mode to html process was never easier</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20221228_elisp-org-publish-blog-configuration.html">Elisp Org-Publish Configuration</a><div class="sitemap-header"><span class="sitemap-date"><2022-07-09 Sat></span><span class="sitemap-tag">blog elisp literateprogramming</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20220527_exporting_org_mode_to_latex_multilanguage.html">Exporting Org Mode to LaTeX and PDFs - Multilanguage</a><div class="sitemap-header"><span class="sitemap-date"><2022-05-27 10:40></span><span class="sitemap-tag">latex org</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/el1/lec_EL1_1_20220407.html">Η δίοδος</a><div class="sitemap-header"><span class="sitemap-date"><2022-04-07></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20220401_to_my_friends.html">With (More Than) A Little Help From My friends</a><div class="sitemap-header"><span class="sitemap-date"><2022-04-01 Fri></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/books/WylieCrawley_ThePentesterBlueprint.html">The Pentester Blueprint</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-30 Wed></span><span class="sitemap-tag">bookreview</span></div><span class="sitemap-description">A review of The Pentester Blueprint: Starting a Career as an Ethical Hacker by Phillip L. Wylie and Kim Crawley. This book serves as a roadmap for aspiring penetration testers, outlining essential skills, education paths, certifications, and hands-on experience needed to break into the field of information security. Rather than teaching technical concepts, it provides guidance, resources, and industry insights to help readers develop a structured approach to becoming a professional pentester.</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/tryhackme/githappens.html">Git Happens</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-26 Sat></span><span class="sitemap-tag">noexport</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/tryhackme/dogcat.html">THM: Dogcat</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-26 Sat></span><span class="sitemap-tag">tryhackme</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/em1/first_order_de.html">Διαφορικές εξισώσεις πρώτης τάξης</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-26 Sat></span></div><span class="sitemap-description">Πιο συγκεκριμένα η επίλυση τους</span></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/books/Mitnick2011-ghostinthewires.html">Ghost in the Wires: My Adventures as the Worlds Most Wanted Hacker</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-26 Sat></span><span class="sitemap-tag">bookreview</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/books/Menn2010_fatalsystemerror.html">Fatal System Error: The Hunt for the New Crime Lords Who Are Bringing Down the Internet</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-26 Sat></span><span class="sitemap-tag">bookreview</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/mit/1802/lec_1802_8_20220320_level_curves_partial_derivatives_tangent_plane_approximation.html">Level curves; partial derivatives; tangent plane approximation</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-19 Sat></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/pts/lec_PTS_2_20220315_lec2.html">Βασικά θεωρήματα και αξιώματα πιθανοτήτων</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-11 Fri></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/auth/pts/lec_PTS_1_20220315_lec1.html">Εισαγωγική Διάλεξη</a><div class="sitemap-header"><span class="sitemap-date"><2022-03-11 Fri></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/mit/6006/6.006-lec-6-binary-trees-part-i.html">6.006 Lec 6: Binary Trees Part I</a><div class="sitemap-header"><span class="sitemap-date"><2022-02-19 Sat></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/mit/6006/6.006-lec-5-linear-sorting.html">6.006 Lec 5: Linear Sorting</a><div class="sitemap-header"><span class="sitemap-date"><2022-02-19 Sat></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/mit/6006/6.006-lec-4-hashing.html">6.006 Lec 4: Hashing</a><div class="sitemap-header"><span class="sitemap-date"><2022-02-18 Wed></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/20220127_first_post.html">Starting again</a><div class="sitemap-header"><span class="sitemap-date"><2022-02-17 Thu></span><span class="sitemap-tag">blog</span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/mit/6006/6.006-lec-3-sorting.html">6.006 Lec 3: Sets and Sorting</a><div class="sitemap-header"><span class="sitemap-date"><2022-02-17 Thu></span></div></div>
<div class="sitemap-item"><a class="sitemap-title" href="/posts/lectures/mit/6006/6.006-lec-2-data-structures-and-dynamic-arrays.html">6.006 Lec 2: Data Structures and Dynamic Arrays</a><div class="sitemap-header"><span class="sitemap-date"><2022-02-16 Wed></span></div></div>
#+end_export