:PROPERTIES:
:ID: lec-TLP1-intro
:END:
#+TITLE: Διάλεξη: 1 Εισαγωγική
#+FILETAGS: lecture
#+DATE: <2022-10-03>
#+FILETAGS: lecture
#+COURSE: TLP1
#+INSTITUTION: A.U.Th


#+begin_definition μάθημα για μηχανικούς
Τεχνικό και όχι μαθηματικά.
#+end_definition

* Σύνοψη
Εισαγωγικό μάθημα, δεν θεωρώ πως είχε κάτι το οποίο θα φανεί ουσιαστικά χρήσιμο
στις επόμενες διαλέξεις.

* Οι τηλεπικοινωνίες έχουν στοχαστική βάση
Γιατί αυτό; Γιατί ο θόρυβος αποτελεί στοχαστικό φαινόμενο.

* Διάκριση θορύβου παρεμβολής
Αν και οι παρεμβολές αποτελούν υποκατηγορία του θορύβου εκείνος θεωρούμε
γενικότερα πως οφείλεται στα ηλεκτρονικά κυκλώματα.

** Θερμικός θόρυβος και ψύξη συστημάτων:
Ο θόρυβος συχνά είναι θερμικός (που σημαίνει ότι είναι ανάλογος της ανόδου της
θερμοκρασίας του κυκλώματος). Για αυτό και σε συστήματα όπως εκείνα των server
είναι απαραίτητη η κατάλληλη ψύξη

* Περί αναλογικής και ψηφιακής τηλεόρασης
Κατά την μετάβαση από την αναλογική στην ψηφιακή τηλεόραση επιτεύχθηκε καλυτερη
ποιότητα και QoS. Αυτή η διαφορά οφείλεται στις διαμορφώσεις (modulations):
αναλογικές και ψηφιακές αντίστοιχα, οι οποίες επιτρέπουν τον περιορισμό του
πλήθους καταστάσεων της εικόνας. Αναλυτικότερα: στις αναλογικές έχουμε άπειρο
αριθμό καταστάσεων ενώ στις ψηφιακές περιορισμένο (σχέση συνεχούς διακριτού
σήματος). Αυτή η ιδιότητα κάνει τις ψηφιακές τηλεοράσεις να αντιμετωπίζουν τον
θόρυβο πολύ καλύτερα.

* Παρουσίαση 5g to 6g 
- Αρχικά έγινε μια σύγκριση των δυο διαφορετικών /σχολών/ της επικοινωνίας:
  εκείνης εστιασμένης στην αποδοτική μεταφορά των μηνυμάτων (Shannon-Weaver) και
  σε εκείνη που αφορά το αποδοτικό περιεχόμενό τους (Umberto Eco)

** Μοντέλο Shannon-Weaver
  - https://www.communicationtheory.org/shannon-and-weaver-model-of-communication/
- Αποστολέας -> Encoder -> Channel -> Decoder -> Receiver
- Προφανώς μπορεί να λειτουργήσει ταυτόχρονα και προς τις δυο πλευρές (
  half-duplex vs full-duplex)
- Κρίσιμες έννοιες:
  - Θόρυβος
  - Εντροπία.

** Ιστορία των τηλεπικοινωνιών
1. Φρυκτώριες (αρχαία υλοποίηση) και αναμετάδοση οπτικού σήματος.
   Χρησιμοποιούνταν ακόμα και στον 18ο αιώνα
2. Marconi
   Ασύρματη επικοινωνία Αγγλίας Γαλλίας.
3. Hedy Lamarr (Hedwig Kiesler)
   Ηθοποιός - ηλεκτρονικός η οποία βοήθησε στην βελτίωση /χειρισμού/ σήματος με θόρυβο.
4. Claude Shannon 
   Δόθηκε μεγάλη έμφαση 



