name: Publish blog

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Install imagemagick
        run: sudo apt install imagemagick --yes

      - name: Build the site
        run: ./build.sh

      - name: Add latest posts
        run: ./latestposts.sh

      - name: Copy index html to secondary location
        run: cp public/index.html public/posts/index.html

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
